
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class Activities extends javax.swing.JFrame {

    /**
     * Creates new form Activities
     */
    public Activities() {
        initComponents();
        AutoInc();
        ShowTabDta();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon myimg = new ImageIcon("C:\\Users\\LENOVO\\Desktop\\900px-NSS-symbol-removebg-preview.png");
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(nsslbl1.getWidth(), nsslbl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        nsslbl1.setIcon(scaledimg);
        nsslbl2.setIcon(scaledimg);
        addbtn.setEnabled(false);
        delebtn.setEnabled(false);
        updtbtn.setEnabled(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\LENOVO\\Desktop\\final_icon_kZY_icon.png"));

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Exit();

            }

        });

    }

    void Exit() {
        int i = JOptionPane.showConfirmDialog(this, "Do You Want To Quit", "Quit", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            Mainscreen m1 = new Mainscreen();
            m1.setVisible(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nsslbl1 = new javax.swing.JLabel();
        nsslbl2 = new javax.swing.JLabel();
        activlbl = new javax.swing.JLabel();
        tasknolbl = new javax.swing.JLabel();
        tasknmlbl = new javax.swing.JLabel();
        facnmlbl = new javax.swing.JLabel();
        taskloclbl = new javax.swing.JLabel();
        taskdurlbl = new javax.swing.JLabel();
        taskyrlbl = new javax.swing.JLabel();
        taskexpen = new javax.swing.JLabel();
        taskcash = new javax.swing.JLabel();
        actinotxt = new javax.swing.JTextField();
        actnametxt = new javax.swing.JTextField();
        facnametxt = new javax.swing.JTextField();
        locnametxt = new javax.swing.JTextField();
        duratxt = new javax.swing.JTextField();
        taskyetxt = new javax.swing.JTextField();
        taskexptxt = new javax.swing.JTextField();
        allcshtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dispdata = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        imglodbtn = new javax.swing.JButton();
        adhdarlbl1 = new javax.swing.JLabel();
        actimage = new javax.swing.JLabel();
        imgloc = new javax.swing.JLabel();
        verifybtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        updtbtn = new javax.swing.JButton();
        delebtn = new javax.swing.JButton();
        exportxls = new javax.swing.JButton();
        serchbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ABSA's NSS Management System 1.0 - Activity ");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setOpaque(false);

        activlbl.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        activlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activlbl.setText("Activity Information");

        tasknolbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tasknolbl.setText("Activity No :");

        tasknmlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tasknmlbl.setText("Activity Name :");

        facnmlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        facnmlbl.setText("Faculty Name :");

        taskloclbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        taskloclbl.setText("Location :");

        taskdurlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        taskdurlbl.setText("Task Duration :");

        taskyrlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        taskyrlbl.setText("Task Year :");

        taskexpen.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        taskexpen.setText("Task Expences :");

        taskcash.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        taskcash.setText("Alloted cash :");

        actinotxt.setEditable(false);
        actinotxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        actinotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        actinotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actinotxtActionPerformed(evt);
            }
        });
        actinotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                actinotxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                actinotxtKeyTyped(evt);
            }
        });

        actnametxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        actnametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        actnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actnametxtActionPerformed(evt);
            }
        });

        facnametxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        facnametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        facnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facnametxtActionPerformed(evt);
            }
        });

        locnametxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        locnametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        locnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locnametxtActionPerformed(evt);
            }
        });

        duratxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        duratxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        duratxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duratxtActionPerformed(evt);
            }
        });

        taskyetxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        taskyetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        taskyetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskyetxtActionPerformed(evt);
            }
        });

        taskexptxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        taskexptxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        taskexptxt.setNextFocusableComponent(allcshtxt);
        taskexptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskexptxtActionPerformed(evt);
            }
        });

        allcshtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        allcshtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        allcshtxt.setNextFocusableComponent(imglodbtn);
        allcshtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allcshtxtActionPerformed(evt);
            }
        });

        dispdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dispdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dispdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dispdata);

        jPanel2.setBackground(new java.awt.Color(255, 255, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imglodbtn.setBackground(new java.awt.Color(255, 255, 255));
        imglodbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        imglodbtn.setText("Load Picture");
        imglodbtn.setNextFocusableComponent(verifybtn);
        imglodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imglodbtnActionPerformed(evt);
            }
        });
        jPanel2.add(imglodbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 416, 194, 43));

        adhdarlbl1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        adhdarlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adhdarlbl1.setText("Image :");
        adhdarlbl1.setToolTipText("");
        jPanel2.add(adhdarlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 424, 44));

        actimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(actimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 60, 270, 300));

        imgloc.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        imgloc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(imgloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 379, 418, 19));

        verifybtn.setBackground(new java.awt.Color(255, 255, 255));
        verifybtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        verifybtn.setText("Verify");
        verifybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifybtnActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updtbtn.setBackground(new java.awt.Color(255, 255, 255));
        updtbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        updtbtn.setText("Update");
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });

        delebtn.setBackground(new java.awt.Color(255, 255, 255));
        delebtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        delebtn.setText("Delete");
        delebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delebtnActionPerformed(evt);
            }
        });

        exportxls.setBackground(new java.awt.Color(255, 255, 255));
        exportxls.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        exportxls.setText("Excel");
        exportxls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportxlsActionPerformed(evt);
            }
        });

        serchbtn.setBackground(new java.awt.Color(255, 255, 255));
        serchbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        serchbtn.setText("Search");
        serchbtn.setNextFocusableComponent(actnametxt);
        serchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchbtnActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(activlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(nsslbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tasknolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tasknmlbl)
                            .addComponent(facnmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskloclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskdurlbl)
                            .addComponent(taskyrlbl)
                            .addComponent(taskexpen)
                            .addComponent(taskcash))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actinotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskyetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskexptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allcshtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updtbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verifybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exportxls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nsslbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(tasknolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(tasknmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(facnmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(taskloclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(taskdurlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(taskyrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(taskexpen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(taskcash, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(actinotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(actnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(facnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(locnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(duratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(taskyetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(taskexptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(allcshtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verifybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exportxls, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actnametxtActionPerformed

    private void facnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facnametxtActionPerformed

    private void locnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locnametxtActionPerformed

    private void duratxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duratxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duratxtActionPerformed

    private void taskyetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskyetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskyetxtActionPerformed

    private void allcshtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allcshtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allcshtxtActionPerformed

    private void taskexptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskexptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskexptxtActionPerformed

    private void actinotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actinotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actinotxtActionPerformed

    private void actinotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_actinotxtKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_actinotxtKeyPressed

    private void actinotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_actinotxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_actinotxtKeyTyped

    private void imglodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imglodbtnActionPerformed
        // TODO add your handling code here:
        //To Load Image
        String loc;
        JFileChooser imgch = new JFileChooser();
        imgch.showOpenDialog(null);
        File f = imgch.getSelectedFile();
        loc = f.getAbsolutePath();
        imgloc.setText(loc);
        ImageIcon myimg = new ImageIcon(loc);
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(actimage.getWidth(), actimage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        actimage.setIcon(scaledimg);
    }//GEN-LAST:event_imglodbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String insq;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String insq2 = "select T_No from Task  where T_No='" + actinotxt.getText() + "'";
            PreparedStatement ptstmt2 = con2.prepareStatement(insq2);
            ResultSet rs2 = ptstmt2.executeQuery();

            if (!rs2.next()) {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                insq = "insert into Task values(?,?,?,?,?,?,?,?,?)";
                PreparedStatement ptstmt = con.prepareStatement(insq);
                //To Add Items Into Database
                ptstmt.setInt(1, Integer.parseInt(actinotxt.getText()));
                ptstmt.setString(2, actnametxt.getText() + " (" + taskyetxt.getText() + ")");
                ptstmt.setString(3, facnametxt.getText());
                ptstmt.setString(4, locnametxt.getText());
                ptstmt.setString(5, duratxt.getText());
                ptstmt.setString(6, taskyetxt.getText());
                ptstmt.setString(7, taskexptxt.getText());
                ptstmt.setString(8, imgloc.getText());
                ptstmt.setString(9, allcshtxt.getText());

                ptstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Inserted Successfully Into Database");
                con.close();
                //To Clear All Feilds
                clear();
                //To See Updated Data In Database
                AutoInc();
                ShowTabDta();
                addbtn.setEnabled(false);
                delebtn.setEnabled(false);
                updtbtn.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(this, "Activity Already Exist Either Click On Update\nOr On Delete Button", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void verifybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifybtnActionPerformed
        // TODO add your handling code here:
        if (!(Pattern.matches("^[a-z A-Z()0-9]{1,40}$", actnametxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Activity Name", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[a-z A-Z]{1,20}$", facnametxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Faculty Name", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (locnametxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Location Field Is Empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]{1,5}$", duratxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Task Duration", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[2][0][0-9]{2}$", taskyetxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Task Year", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (taskexptxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Expences", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (allcshtxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Alloted Cash", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (imgloc.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Choose An Image", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Verified");
            addbtn.setEnabled(true);
            delebtn.setEnabled(true);
            updtbtn.setEnabled(true);
        }


    }//GEN-LAST:event_verifybtnActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
        // TODO add your handling code here:
        String Upsql;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            Upsql = "Update Task Set T_Name=?,F_Name=?,T_Loc=?,T_Dur=?,T_Year=?,T_Expence=?,Image=?,Cash=? where T_No=?";
            PreparedStatement ptstmt = con.prepareStatement(Upsql);
            ptstmt.setInt(9, Integer.parseInt(actinotxt.getText()));
            ptstmt.setString(1, actnametxt.getText());
            ptstmt.setString(2, facnametxt.getText());
            ptstmt.setString(3, locnametxt.getText());
            ptstmt.setString(4, duratxt.getText());
            ptstmt.setString(5, taskyetxt.getText());
            ptstmt.setString(6, taskexptxt.getText());
            ptstmt.setString(7, imgloc.getText());
            ptstmt.setString(8, allcshtxt.getText());
            ptstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Updated Details Successfully Into Database");

            clear();
            AutoInc();
            ShowTabDta();
            addbtn.setEnabled(false);
            delebtn.setEnabled(false);
            updtbtn.setEnabled(false);

        } catch (Exception e) {
            System.out.println("" + e);
        }

    }//GEN-LAST:event_updtbtnActionPerformed

    private void delebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delebtnActionPerformed
        // TODO add your handling code here:
        String Delq;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            Delq = "delete from Task where T_No='" + actinotxt.getText() + "'";
            PreparedStatement delptstmt = con.prepareStatement(Delq);
            //delptstmt.setInt(1,Integer.parseInt());
            delptstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Deleted Record Successfully From Database Database");
            con.close();

            clear();
            ShowTabDta();
            AutoInc();
            addbtn.setEnabled(false);
            delebtn.setEnabled(false);
            updtbtn.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_delebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Mainscreen m1 = new Mainscreen();
        m1.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void dispdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispdataMouseClicked
        // TODO add your handling code here:
        int i = dispdata.getSelectedRow();
        TableModel M1 = dispdata.getModel();
        actinotxt.setText(M1.getValueAt(i, 0).toString());
        actnametxt.setText(M1.getValueAt(i, 1).toString());

        facnametxt.setText(M1.getValueAt(i, 2).toString());
        locnametxt.setText(M1.getValueAt(i, 3).toString());
        duratxt.setText(M1.getValueAt(i, 4).toString());
        taskyetxt.setText(M1.getValueAt(i, 5).toString());
        taskexptxt.setText(M1.getValueAt(i, 6).toString());
        imgloc.setText(M1.getValueAt(i, 7).toString());
        allcshtxt.setText(M1.getValueAt(i, 8).toString());
        //Load Image After Click On Table Row
        ImageIcon myimg = new ImageIcon(imgloc.getText());
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(actimage.getWidth(), actimage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        actimage.setIcon(scaledimg);

    }//GEN-LAST:event_dispdataMouseClicked

    private void serchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchbtnActionPerformed
        // TODO add your handling code here:
        clear();
        String nm = JOptionPane.showInputDialog(this, "Enter The Enrollment ID Of Student");

        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select * from Task where T_No='" + nm + "'";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                actinotxt.setText(rs.getString(1));
                actnametxt.setText(rs.getString(2));
                facnametxt.setText(rs.getString(3));
                locnametxt.setText(rs.getString(4));
                duratxt.setText(rs.getString(5));
                taskyetxt.setText(rs.getString(6));
                taskexptxt.setText(rs.getNString(7));
                imgloc.setText(rs.getString(8));
                allcshtxt.setText(rs.getString(9));
                ImageIcon myimg = new ImageIcon(imgloc.getText());
                Image img1 = myimg.getImage();
                Image img2 = img1.getScaledInstance(actimage.getWidth(), actimage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledimg = new ImageIcon(img2);
                actimage.setIcon(scaledimg);
                updtbtn.setEnabled(true);
                delebtn.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(this, "Activity Is Not Added ", "Error", JOptionPane.ERROR_MESSAGE);
                addbtn.setEnabled(false);
                AutoInc();

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_serchbtnActionPerformed

    private void exportxlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportxlsActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\LENOVO\\Desktop\\Exported Files";
        JFileChooser ExcelExport = new JFileChooser(path);
        int excelChooser = ExcelExport.showSaveDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {

            XSSFWorkbook wb = new XSSFWorkbook();
            XSSFSheet ws = wb.createSheet("Activity Details");

            for (int i = 0; i < dispdata.getRowCount(); i++) {

                XSSFRow r = ws.createRow(i);

                for (int j = 0; j < dispdata.getColumnCount(); j++) {

                    XSSFCell c = r.createCell(j);

                    c.setCellValue(dispdata.getValueAt(i, j).toString());
                }
            }
            FileOutputStream exclfile;
            BufferedOutputStream excelbu;
            try {
                exclfile = new FileOutputStream(ExcelExport.getSelectedFile() + ".xlsx");

                excelbu = new BufferedOutputStream(exclfile);
                wb.write(excelbu);
                excelbu.close();
                wb.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_exportxlsActionPerformed

    public void clear() {
        actinotxt.setText("");
        actnametxt.setText("");
        facnametxt.setText("");
        locnametxt.setText("");
        duratxt.setText("");
        taskyetxt.setText("");
        taskexptxt.setText("");
        imgloc.setText("");
        allcshtxt.setText("");
        actimage.setIcon(null);
    }

    public void ShowTabDta() {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select * from Task";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            dispdata.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void AutoInc() {
        String selc = "select Max(T_No) from Task";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement selpst = con.prepareStatement(selc);
            ResultSet rs = selpst.executeQuery();
            if (rs.next()) {
                int auto = rs.getInt(1);
                int autoin = auto + 1;
                actinotxt.setText(Integer.toString(autoin));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        try {
            UIManager.setLookAndFeel(new TextureLookAndFeel());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activities().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actimage;
    private javax.swing.JTextField actinotxt;
    private javax.swing.JLabel activlbl;
    private javax.swing.JTextField actnametxt;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel adhdarlbl1;
    private javax.swing.JTextField allcshtxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton delebtn;
    private javax.swing.JTable dispdata;
    private javax.swing.JTextField duratxt;
    private javax.swing.JButton exportxls;
    private javax.swing.JTextField facnametxt;
    private javax.swing.JLabel facnmlbl;
    private javax.swing.JLabel imgloc;
    private javax.swing.JButton imglodbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locnametxt;
    private javax.swing.JLabel nsslbl1;
    private javax.swing.JLabel nsslbl2;
    private javax.swing.JButton serchbtn;
    private javax.swing.JLabel taskcash;
    private javax.swing.JLabel taskdurlbl;
    private javax.swing.JLabel taskexpen;
    private javax.swing.JTextField taskexptxt;
    private javax.swing.JLabel taskloclbl;
    private javax.swing.JLabel tasknmlbl;
    private javax.swing.JLabel tasknolbl;
    private javax.swing.JTextField taskyetxt;
    private javax.swing.JLabel taskyrlbl;
    private javax.swing.JButton updtbtn;
    private javax.swing.JButton verifybtn;
    // End of variables declaration//GEN-END:variables
}
