
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.io.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LENOVO
 */
public class AssignActivity extends javax.swing.JFrame {

    /**
     * Creates new form AssignActivity
     */
    String E, A;

    public AssignActivity() {
        initComponents();
        ShowTabDta();
        DropdownSNO();
        DropdownTNO();
        Autoinc();
        taskno.setSelectedIndex(0);
        studno.setSelectedIndex(0);
        tasknametxt.setText("");
        studnametxt.setText("");
        studclstxt.setText("");
        taskdurtxt.setText("");

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon myimg = new ImageIcon("C:\\Users\\LENOVO\\Desktop\\900px-NSS-symbol-removebg-preview.png");
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(nsslbl1.getWidth(), nsslbl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        nsslbl1.setIcon(scaledimg);
        nsslbl3.setIcon(scaledimg);
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\LENOVO\\Desktop\\final_icon_kZY_icon.png"));
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Exit();

            }

        });
    }
    void Exit() {
        int i = JOptionPane.showConfirmDialog(this, "Do You Want To Quit", "Quit", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            Mainscreen m1 = new Mainscreen();
            m1.setVisible(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nsslbl1 = new javax.swing.JLabel();
        nsslbl3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        taskno = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studno = new javax.swing.JComboBox<>();
        tasknametxt = new javax.swing.JTextField();
        taskdurtxt = new javax.swing.JTextField();
        studnametxt = new javax.swing.JTextField();
        studclstxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dispdata = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        assigntxt = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        deletbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        deletbtn1 = new javax.swing.JButton();
        updtbtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ABSA's NSS Management System 1.0 - Assign Activity");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Assign Activity");

        taskno.setToolTipText("");
        taskno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tasknoItemStateChanged(evt);
            }
        });
        taskno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasknoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("Task No :");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel2.setText("Student Class :");

        studno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studnoActionPerformed(evt);
            }
        });

        tasknametxt.setEditable(false);
        tasknametxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        tasknametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        taskdurtxt.setEditable(false);
        taskdurtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        taskdurtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        studnametxt.setEditable(false);
        studnametxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        studnametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        studclstxt.setEditable(false);
        studclstxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        studclstxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setText("Task Duration (hrs) :");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setText("Task Name :");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setText("Student No :");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setText("Student Name :");

        Dispdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Dispdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Dispdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DispdataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Dispdata);

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setText("Assignment No :");

        assigntxt.setEditable(false);
        assigntxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        assigntxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        deletbtn.setBackground(new java.awt.Color(255, 255, 255));
        deletbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        deletbtn.setText("Delete");
        deletbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletbtnActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(255, 255, 255));
        searchbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        deletbtn1.setBackground(new java.awt.Color(255, 255, 255));
        deletbtn1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        deletbtn1.setText("Excel");
        deletbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletbtn1ActionPerformed(evt);
            }
        });

        updtbtn.setBackground(new java.awt.Color(255, 255, 255));
        updtbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        updtbtn.setText("Update");
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nsslbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tasknametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(taskno, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(assigntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(taskdurtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(deletbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(225, 225, 225)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(studno, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(studclstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(studnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(deletbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nsslbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assigntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tasknametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studclstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskdurtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 800));

        getAccessibleContext().setAccessibleName("ABSA's NSS Management System 1.0 - Assign Activity");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tasknoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tasknoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_tasknoItemStateChanged

    private void tasknoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasknoActionPerformed
        // TODO add your handling code here:
        String Sel = taskno.getSelectedItem().toString();
        String qry = "select T_Name, T_Dur from Task where T_No='" + Sel + "'";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement ptstmt = con.prepareStatement(qry);
            ResultSet rs = ptstmt.executeQuery();
            while (rs.next()) {
                tasknametxt.setText(rs.getString(1));
                taskdurtxt.setText(rs.getString(2));
                A = tasknametxt.getText();
            }
        } catch (Exception se) {
            JOptionPane.showMessageDialog(this, "" + se);

        }

    }//GEN-LAST:event_tasknoActionPerformed

    private void studnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnoActionPerformed
        // TODO add your handling code here:
        String Sel = studno.getSelectedItem().toString();
        String qry = "select S_Name, Class ,Email from Student where E_Id='" + Sel + "'";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement ptstmt = con.prepareStatement(qry);
            ResultSet rs = ptstmt.executeQuery();
            while (rs.next()) {
                studnametxt.setText(rs.getString(1));
                studclstxt.setText(rs.getString(2));
                E = rs.getString(3);
            }

        } catch (Exception se) {
            JOptionPane.showMessageDialog(this, "" + se);

        }
    }//GEN-LAST:event_studnoActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String insq;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String insq2 = "select A_No from Stud_Task  where A_No='" + assigntxt.getText() + "'";

            PreparedStatement ptstmt2 = con2.prepareStatement(insq2);
            ResultSet rs2 = ptstmt2.executeQuery();
            if (!rs2.next()) {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                insq = "insert into Stud_Task values(?,?,?,?,?,?,?)";
                PreparedStatement ptstmt = con.prepareStatement(insq);
                //To Add Items Into Database
                ptstmt.setInt(1, Integer.parseInt(taskno.getSelectedItem().toString()));
                ptstmt.setInt(2, Integer.parseInt(studno.getSelectedItem().toString()));
                ptstmt.setString(3, tasknametxt.getText());
                ptstmt.setString(4, studnametxt.getText());
                ptstmt.setString(5, studclstxt.getText());
                ptstmt.setString(6, taskdurtxt.getText());
                ptstmt.setString(7, assigntxt.getText());
                ptstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Inserted Successfully Into Database");
                sendmail(E, A);
                con.close();
                clear();
                ShowTabDta();
                Autoinc();
                
            } 
            
            else {
                JOptionPane.showMessageDialog(this, "Activity Already Assigned To Student\n Either Click On Update Or On Delete Button", "Error", JOptionPane.ERROR_MESSAGE);            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_addbtnActionPerformed

    public void clear() {
        taskno.setSelectedIndex(0);
        studno.setSelectedIndex(0);
        tasknametxt.setText("");
        studnametxt.setText("");
        studclstxt.setText("");
        taskdurtxt.setText("");
        assigntxt.setText("");
    }
    private void deletbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletbtnActionPerformed
        // TODO add your handling code here:
        String Delq;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            Delq = "delete from Stud_Task where A_No='" + assigntxt.getText() + "'";
            PreparedStatement delptstmt = con.prepareStatement(Delq);
            //delptstmt.setInt(1,Integer.parseInt());
            delptstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Deleted Record Successfully From Database Database");
            con.close();
            clear();
            Autoinc();
            ShowTabDta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_deletbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Mainscreen M1 = new Mainscreen();
        M1.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        clear();
        String nm = JOptionPane.showInputDialog(this, "Enter The Assignment No Of Student");

        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select * from Stud_Task where A_No='" + nm + "'";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                taskno.setSelectedItem(rs.getString(1));
                studno.setSelectedItem(rs.getString(2));
                tasknametxt.setText(rs.getString(3));
                studnametxt.setText(rs.getString(4));
                studclstxt.setText(rs.getString(5));
                taskdurtxt.setText(rs.getString(6));
                assigntxt.setText(rs.getString(7));
            } else {

                JOptionPane.showMessageDialog(this, "Assignment Is Not Available", "Error", JOptionPane.ERROR_MESSAGE);//

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_searchbtnActionPerformed


    private void DispdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DispdataMouseClicked
        // TODO add your handling code here:
        int i = Dispdata.getSelectedRow();
        TableModel M1 = Dispdata.getModel();
        assigntxt.setText(M1.getValueAt(i, 6).toString());
        taskno.setSelectedItem(M1.getValueAt(i,0).toString());
        studno.setSelectedItem(M1.getValueAt(i,1).toString());
        

    }//GEN-LAST:event_DispdataMouseClicked

    private void deletbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletbtn1ActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\LENOVO\\Desktop\\Exported Files";
        JFileChooser ExcelExport = new JFileChooser(path);
        int excelChooser = ExcelExport.showSaveDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {

            XSSFWorkbook wb = new XSSFWorkbook();
            XSSFSheet ws = wb.createSheet("Assigned Activity Details");

            for (int i = 0; i < Dispdata.getRowCount(); i++) {

                XSSFRow r = ws.createRow(i);

                for (int j = 0; j < Dispdata.getColumnCount(); j++) {

                    XSSFCell c = r.createCell(j);

                    c.setCellValue(Dispdata.getValueAt(i, j).toString());
                }
            }
            FileOutputStream exclfile;
            BufferedOutputStream excelbu;
            try {
                exclfile = new FileOutputStream(ExcelExport.getSelectedFile() + ".xlsx");

                excelbu = new BufferedOutputStream(exclfile);
                wb.write(excelbu);
                excelbu.close();
                wb.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_deletbtn1ActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
        // TODO add your handling code here:
         String Upsql;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            Upsql = "Update Stud_Task Set T_No=?,S_No=?,T_Name=?,S_Name=?,Class=?,T_Dur=? where A_No=?";
            PreparedStatement ptstmt = con.prepareStatement(Upsql);
            ptstmt.setInt(7, Integer.parseInt(assigntxt.getText()));
            ptstmt.setString(1, taskno.getSelectedItem().toString());
            ptstmt.setString(2, studno.getSelectedItem().toString());
            ptstmt.setString(3, tasknametxt.getText());
            ptstmt.setString(4, studnametxt.getText());
            ptstmt.setString(5, studclstxt.getText());
            ptstmt.setString(6, taskdurtxt.getText());
            ptstmt.executeUpdate();
            ptstmt.close();
            con.close();
            JOptionPane.showMessageDialog(this, "Updated Successfully Into Database");
            ShowTabDta();
            clear();
            Autoinc();
            
        }   
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_updtbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void ShowTabDta() {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select * from Stud_Task";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            Dispdata.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void Autoinc() {
        String selc = "select Max(A_No) from Stud_Task";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement selpst = con.prepareStatement(selc);
            ResultSet rs = selpst.executeQuery();
            if (rs.next()) {
                int auto = rs.getInt(1);
                int autoin = auto + 1;
                assigntxt.setText(Integer.toString(autoin));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    public void DropdownTNO() {
        String drpdwn = "select T_No from Task";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement ptstmt = con.prepareStatement(drpdwn);
            ResultSet rs = ptstmt.executeQuery();
            while (rs.next()) {
                taskno.addItem(rs.getString(1));
            }

        } catch (Exception se) {
            JOptionPane.showMessageDialog(this, "" + se);

        }
    }

    public void DropdownSNO() {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select E_Id from Student";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                studno.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public static void sendmail(String R, String Act) {

        try {
            JOptionPane.showMessageDialog(null, "Preparing To Send Mail");
            Properties p = new Properties();
            p.put("mail.smtp.port", "587");

            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com");

            String From = "nss.acacs@gmail.com";
            String EPass = "Arihant2020";
            String Sub = "Reset Password";
            String Txt = "Hello Students....!\n You Get An Activity Of " + Act + "\n All The Best For Your Activity.";

            Session s = Session.getDefaultInstance(p, new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(From, EPass);
                }
            });
            Message M = prepareMessage(s, From, R, Sub, Txt);
            Transport.send(M);
            JOptionPane.showMessageDialog(null, "Email sended To " + R + "");
        } catch (MessagingException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    private static Message prepareMessage(Session s, String From, String R, String Sub, String Txt) {
        try {
            Message M = new MimeMessage(s);
            M.setFrom(new InternetAddress(From));
            M.setRecipient(Message.RecipientType.TO, new InternetAddress(R));
            M.setSubject(Sub);
            M.setText(Txt);
            return M;

        } catch (Exception e) {
            System.out.println("" + e);
        }
        return null;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/
       try{
            UIManager.setLookAndFeel(new TextureLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, ""+e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Dispdata;
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField assigntxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deletbtn;
    private javax.swing.JButton deletbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nsslbl1;
    private javax.swing.JLabel nsslbl3;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField studclstxt;
    private javax.swing.JTextField studnametxt;
    private javax.swing.JComboBox<String> studno;
    private javax.swing.JTextField taskdurtxt;
    private javax.swing.JTextField tasknametxt;
    private javax.swing.JComboBox<String> taskno;
    private javax.swing.JButton updtbtn;
    // End of variables declaration//GEN-END:variables

    private void setMaximizedBounds(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
