import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class Frontpage extends javax.swing.JFrame {

    /**
     * Creates new form Splashscreen
     */
    public Frontpage() {
        initComponents();
        ImageIcon myimg = new ImageIcon("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\NSS Management System\\src\\Logo Front 1.jpg");
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(displbl.getWidth(), displbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        displbl.setIcon(scaledimg);
       setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\LENOVO\\Desktop\\final_icon_kZY_icon.png"));
       /*ImageIcon myimg2 = new ImageIcon("‪C:\\Users\\LENOVO\\Desktop\\JAVA stuff\\Loading 1.gif");
        Image img3 = myimg2.getImage();
        Image img4 = img3.getScaledInstance(displbl.getWidth(), displbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg2 = new ImageIcon(img4);
        jLabel1.setIcon(scaledimg2);*/
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadlbl = new javax.swing.JLabel();
        loadbar = new javax.swing.JProgressBar();
        loadlbl1 = new javax.swing.JLabel();
        displbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABSA's NSS Management System 1.0 - Splash Screen");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadlbl.setFont(new java.awt.Font("Lucida Sans", 2, 12)); // NOI18N
        loadlbl.setForeground(java.awt.SystemColor.control);
        loadlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadlbl.setText("0");
        jPanel1.add(loadlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 220, 30));

        loadbar.setBackground(new java.awt.Color(255, 255, 255));
        loadbar.setForeground(new java.awt.Color(51, 51, 51));
        loadbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loadbar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                loadbarPropertyChange(evt);
            }
        });
        jPanel1.add(loadbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 333, 530, 10));

        loadlbl1.setFont(new java.awt.Font("Lucida Sans", 2, 12)); // NOI18N
        loadlbl1.setForeground(java.awt.SystemColor.control);
        loadlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadlbl1.setText("ABSA's NSS Management System 1.0");
        jPanel1.add(loadlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 370));

        displbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(displbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadbarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_loadbarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_loadbarPropertyChange

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>/*
        
        
        /* Create and display the form */
       try {
            UIManager.setLookAndFeel(new TextureLookAndFeel());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }
        
        Frontpage front =new Frontpage();
        front.setVisible(true);
        
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep(100);
                loadlbl.setText("Loading " +(Integer.toString(i))+" %");
                loadbar.setValue(i);
                if(i==100){
                   Helloframe h1 =new Helloframe();
                    h1.setVisible(true);
                    front.dispose();
                  }
                }
        }
        catch(Exception e){
            System.out.println(""+e);
        }
        
        
                
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displbl;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JProgressBar loadbar;
    public static javax.swing.JLabel loadlbl;
    public static javax.swing.JLabel loadlbl1;
    // End of variables declaration//GEN-END:variables

    
}
