
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LENOVO
 */
public class Galleria extends javax.swing.JFrame {

    /**
     * Creates new form Galleria
     */
    private ArrayList<String> Studnm;
    public ListIterator<String> listitr;
    int size;

    public Galleria() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon myimg = new ImageIcon("C:\\Users\\LENOVO\\Desktop\\900px-NSS-symbol-removebg-preview.png");
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(nsslbl1.getWidth(), nsslbl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        nsslbl1.setIcon(scaledimg);
        nsslbl3.setIcon(scaledimg);
        DropdownTNO();
        taskno.setSelectedIndex(0);
        tasknoimgview.setSelectedIndex(0);
        tasknametxt.setText("");
        //firstImage();
        imgbiewlbl.setIcon(null);
        deletebtn.setEnabled(false);
        ShowTabDta();
        AutoInc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nsslbl1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nsslbl3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dispdata = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        tasknametxt = new javax.swing.JTextField();
        tasknmlbl = new javax.swing.JLabel();
        tasknolbl = new javax.swing.JLabel();
        taskno = new javax.swing.JComboBox<>();
        deletebtn = new javax.swing.JButton();
        delimglbl = new javax.swing.JLabel();
        imgnotxt = new javax.swing.JTextField();
        tasknolbl2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tasknolbl1 = new javax.swing.JLabel();
        tasknoimgview = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        imgbiewlbl = new javax.swing.JLabel();
        prevbtn = new javax.swing.JButton();
        nextbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nsslbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 131, 121));

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Galleria");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 27, 1226, 121));
        jPanel1.add(nsslbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1379, 27, 131, 121));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add Images", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 18))); // NOI18N

        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        dispdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dispdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dispdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dispdata);
        dispdata.getAccessibleContext().setAccessibleName("");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Activity Info", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N

        tasknametxt.setEditable(false);
        tasknametxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        tasknametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tasknmlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tasknmlbl.setText("Activity Name :");

        tasknolbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tasknolbl.setText("Activity No :");

        taskno.setEditable(true);
        taskno.setToolTipText("");
        taskno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tasknoItemStateChanged(evt);
            }
        });
        taskno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasknoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tasknolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tasknmlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tasknametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskno, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tasknolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tasknmlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tasknametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deletebtn.setBackground(new java.awt.Color(255, 255, 255));
        deletebtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        delimglbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgnotxt.setEditable(false);
        imgnotxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        imgnotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tasknolbl2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tasknolbl2.setText("Image No:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tasknolbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(delimglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tasknolbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(delimglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 205, 510, 590));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Surf Images", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 18))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Activity Info", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N

        tasknolbl1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tasknolbl1.setText("Activity No :");

        tasknoimgview.setEditable(true);
        tasknoimgview.setToolTipText("");
        tasknoimgview.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tasknoimgviewItemStateChanged(evt);
            }
        });
        tasknoimgview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasknoimgviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tasknolbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tasknoimgview, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tasknoimgview, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tasknolbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N

        imgbiewlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        prevbtn.setBackground(new java.awt.Color(255, 255, 255));
        prevbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        prevbtn.setText("Prev");
        prevbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevbtnActionPerformed(evt);
            }
        });

        nextbtn.setBackground(new java.awt.Color(255, 255, 255));
        nextbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        nextbtn.setText("Next");
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(prevbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imgbiewlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgbiewlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(prevbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 205, -1, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 1520, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tasknoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tasknoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tasknoItemStateChanged

    private void tasknoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasknoActionPerformed
        // TODO add your handling code here:
        String Sel = taskno.getSelectedItem().toString();
        String qry = "select T_Name from Task where T_No='" + Sel + "'";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement ptstmt = con.prepareStatement(qry);
            ResultSet rs = ptstmt.executeQuery();
            while (rs.next()) {
                tasknametxt.setText(rs.getString(1));

            }
        } catch (Exception se) {
            JOptionPane.showMessageDialog(this, "" + se);

        }
    }//GEN-LAST:event_tasknoActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        try {
            if (tasknametxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please Select Activity Name");
            } else {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                String insq = "insert into Galleria values(?,?,?)";
                PreparedStatement ptstmt = con.prepareStatement(insq);
                String loc = null;
                String x = JOptionPane.showInputDialog(this, "How Many Images You Want To Add?");
                int n = Integer.parseInt(x);
                for (int i = 1; i <= n; i++) {
                    JFileChooser imgch = new JFileChooser();
                    int a = imgch.showOpenDialog(null);
                    File f = imgch.getSelectedFile();
                    if (a == JFileChooser.APPROVE_OPTION) {
                        loc = f.getAbsolutePath();
                        ptstmt.setInt(1, Integer.parseInt(taskno.getSelectedItem().toString()));
                        ptstmt.setString(2, loc);
                        ptstmt.setInt(3, Integer.parseInt(imgnotxt.getText()));
                        ptstmt.executeUpdate();
                        AutoInc();
                        ShowTabDta();
                        tasknoimgview.setSelectedIndex(0);
                        imgbiewlbl.setIcon(null);
                        JOptionPane.showMessageDialog(this, "Inserted Successfully In the Database");
                    } else if (a == JFileChooser.CANCEL_OPTION) {
                        JOptionPane.showMessageDialog(this, "No file Is Selectd", "Null File", JOptionPane.ERROR_MESSAGE);
                        i--;
                    } else {
                        JOptionPane.showMessageDialog(this, "No file Is Selectd", "Null File", JOptionPane.ERROR_MESSAGE);
                        i--;
                    }
                }
                tasknametxt.setText("");
            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_addbtnActionPerformed

    private void tasknoimgviewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tasknoimgviewItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_tasknoimgviewItemStateChanged

    private void tasknoimgviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasknoimgviewActionPerformed
        try {
            String Sel = tasknoimgview.getSelectedItem().toString();
            String qry = "select G_Img from Galleria where G_A_No='" + Sel + "'";

            Class.forName("com.mysql.jdbc.Driver");
            Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement ptstmt2 = con2.prepareStatement(qry);
            ResultSet rs2 = ptstmt2.executeQuery();
            if (rs2.next()) {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                PreparedStatement ptstmt = con.prepareStatement(qry);
                ResultSet rs = ptstmt.executeQuery();
                Studnm = new ArrayList<String>();

                while (rs.next()) {
                    Studnm.add(rs.getString(1));
                }
                firstImage();

            } else {
                imgbiewlbl.setIcon(null);
                tasknoimgview.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "No Images Inserted For Activity Number " + Sel, "Null Images", JOptionPane.ERROR_MESSAGE);
                firstImage();

            }
        } catch (Exception se) {
            JOptionPane.showMessageDialog(this, "" + se);

        }
        /*for(int i = 0 ; i< Studnm.size();i++){
            JOptionPane.showMessageDialog(this, Studnm.get(i));
        }*/

    }//GEN-LAST:event_tasknoimgviewActionPerformed

    private void prevbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevbtnActionPerformed
        if (listitr.hasPrevious()) {
            String s;
            s = listitr.previous();
            ImageIcon myimg = new ImageIcon(s);
            Image img1 = myimg.getImage();
            Image img2 = img1.getScaledInstance(imgbiewlbl.getWidth(), imgbiewlbl.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledimg = new ImageIcon(img2);
            imgbiewlbl.setIcon(scaledimg);
        } else {
            JOptionPane.showMessageDialog(this, "First Record");
        }
    }//GEN-LAST:event_prevbtnActionPerformed

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
        if (listitr.hasNext()) {
            String s;
            s = listitr.next();
            ImageIcon myimg = new ImageIcon(s);
            Image img1 = myimg.getImage();
            Image img2 = img1.getScaledInstance(imgbiewlbl.getWidth(), imgbiewlbl.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledimg = new ImageIcon(img2);
            imgbiewlbl.setIcon(scaledimg);

        } else {
            JOptionPane.showMessageDialog(this, "Last Record");
        }
    }//GEN-LAST:event_nextbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        String Delq;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            Delq = "delete from Galleria where G_I_No='" + imgnotxt.getText() + "'";
            PreparedStatement delptstmt = con.prepareStatement(Delq);
            //delptstmt.setInt(1,Integer.parseInt());
            delptstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Deleted Record Successfully From Database Database");
            con.close();
            ShowTabDta();
            AutoInc();
            deletebtn.setEnabled(false);
            delimglbl.setIcon(null);
            tasknoimgview.setSelectedIndex(0);
            imgbiewlbl.setIcon(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void dispdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispdataMouseClicked
        // TODO add your handling code here:
        int i = dispdata.getSelectedRow();
        TableModel M1 = dispdata.getModel();
        ImageIcon myimg = new ImageIcon(M1.getValueAt(i, 1).toString());
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(delimglbl.getWidth(), delimglbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        delimglbl.setIcon(scaledimg);
        imgnotxt.setText(M1.getValueAt(i, 2).toString());
        deletebtn.setEnabled(true);

    }//GEN-LAST:event_dispdataMouseClicked

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Mainscreen M1 = new Mainscreen();
        M1.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    public void DropdownTNO() {
        String drpdwn = "select T_No from Task";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement ptstmt = con.prepareStatement(drpdwn);
            ResultSet rs = ptstmt.executeQuery();
            while (rs.next()) {
                taskno.addItem(rs.getString(1));
                tasknoimgview.addItem(rs.getString(1));
            }

        } catch (Exception se) {
            JOptionPane.showMessageDialog(this, "" + se);

        }
    }

    public void ShowTabDta() {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select * from Galleria";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            dispdata.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void firstImage() {
        size = 0;
        listitr = Studnm.listIterator();
        String s;
        s = listitr.next();
        ImageIcon myimg1 = new ImageIcon(s);
        Image img3 = myimg1.getImage();
        Image img4 = img3.getScaledInstance(imgbiewlbl.getWidth(), imgbiewlbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg1 = new ImageIcon(img4);
        imgbiewlbl.setIcon(scaledimg1);
    }

    public void AutoInc() {
        String selc = "select Max(G_I_No) from Galleria";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement selpst = con.prepareStatement(selc);
            ResultSet rs = selpst.executeQuery();
            if (rs.next()) {
                int auto = rs.getInt(1);
                int autoin = auto + 1;
                imgnotxt.setText(Integer.toString(autoin));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Galleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Galleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Galleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Galleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/
        try {
            UIManager.setLookAndFeel(new TextureLookAndFeel());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Galleria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel delimglbl;
    private javax.swing.JTable dispdata;
    private javax.swing.JLabel imgbiewlbl;
    private javax.swing.JTextField imgnotxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextbtn;
    private javax.swing.JLabel nsslbl1;
    private javax.swing.JLabel nsslbl3;
    private javax.swing.JButton prevbtn;
    private javax.swing.JTextField tasknametxt;
    private javax.swing.JLabel tasknmlbl;
    private javax.swing.JComboBox<String> taskno;
    private javax.swing.JComboBox<String> tasknoimgview;
    private javax.swing.JLabel tasknolbl;
    private javax.swing.JLabel tasknolbl1;
    private javax.swing.JLabel tasknolbl2;
    // End of variables declaration//GEN-END:variables
}
