
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class Mainscreen extends javax.swing.JFrame {

    /**
     * Creates new form Mainscreen
     */
    public Mainscreen() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\LENOVO\\Desktop\\final_icon_kZY_icon.png"));
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Exit();
                
            }
            
        });
        ImageIcon myimg1=new ImageIcon("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\NSS Management System\\src\\IMG-20191219-WA0009.jpg");
        Image img1 = myimg1.getImage();
        Image img2 = img1.getScaledInstance(nsmg1.getWidth(),nsmg1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledimg =new ImageIcon(img2);
        nsmg1.setIcon(scaledimg);
        
        ImageIcon myimg2=new ImageIcon("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\NSS Management System\\src\\IMG_20191221_170107.jpg");
        Image img3 = myimg2.getImage();
        Image img4 = img3.getScaledInstance(nsmg1.getWidth(),nsmg1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledimg1 =new ImageIcon(img4);
        nsmg2.setIcon(scaledimg1);
        
        ImageIcon myimg3=new ImageIcon("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\NSS Management System\\src\\IMG-20191219-WA0004.jpg");
        Image img5 = myimg3.getImage();
        Image img6 = img5.getScaledInstance(nsmg1.getWidth(),nsmg1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledimg2 =new ImageIcon(img6);
        nsmg3.setIcon(scaledimg2);
        
       ImageIcon myimg4=new ImageIcon("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\NSS Management System\\src\\IMG-20191221-WA0002.jpg");
        Image img7 = myimg4.getImage();
        Image img8 = img7.getScaledInstance(nsmg1.getWidth(),nsmg1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledimg3 =new ImageIcon(img8);
        nsmg4.setIcon(scaledimg3);
        
        ImageIcon myimg5=new ImageIcon("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\NSS Management System\\src\\IMG-20191221-WA0039.jpg");
        Image img9 = myimg5.getImage();
        Image img10 = img9.getScaledInstance(nsmg1.getWidth(),nsmg1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledimg4 =new ImageIcon(img10);
        nsmg5.setIcon(scaledimg4);
        
        ImageIcon myimg6=new ImageIcon("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\NSS Management System\\src\\IMG_7950.JPG");
        Image img11 = myimg6.getImage();
        Image img12 = img11.getScaledInstance(nsmg1.getWidth(),nsmg1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledimg5 =new ImageIcon(img12);
        nsmg6.setIcon(scaledimg5);
        
        ImageIcon myimg7=new ImageIcon("C:\\Users\\LENOVO\\Desktop\\Student.png");
        Image img13 = myimg7.getImage();
        Image img14 = img13.getScaledInstance(studmg.getWidth(),studmg.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledimg6 =new ImageIcon(img14);
        studmg.setIcon(scaledimg6);
        
        ImageIcon myimg8 =new ImageIcon("C:\\Users\\LENOVO\\Desktop\\Activity.png");
        Image img15 = myimg8.getImage();
        Image img16 = img15.getScaledInstance(studmg.getWidth(),studmg.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledimg7 =new ImageIcon(img16);
        activmg.setIcon(scaledimg7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nsmg1 = new javax.swing.JLabel();
        nsmg2 = new javax.swing.JLabel();
        nsmg3 = new javax.swing.JLabel();
        nsmg4 = new javax.swing.JLabel();
        nsmg5 = new javax.swing.JLabel();
        nsmg6 = new javax.swing.JLabel();
        studmg = new javax.swing.JLabel();
        activmg = new javax.swing.JLabel();
        shwstud = new javax.swing.JButton();
        shwactivity = new javax.swing.JButton();
        shwactivity1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        assigntsk = new javax.swing.JMenu();
        sendml = new javax.swing.JMenu();
        reportsrshow = new javax.swing.JMenu();
        about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ABSA's NSS Management System 1.0 - Main Screen");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("National Service Scheme Management System 1.0");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 199));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Activity Records");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Student Records");

        nsmg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nsmg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nsmg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nsmg4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nsmg5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nsmg6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        studmg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        activmg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        shwstud.setBackground(new java.awt.Color(255, 255, 255));
        shwstud.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        shwstud.setText("Click Here ");
        shwstud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shwstud.setName(""); // NOI18N
        shwstud.setNextFocusableComponent(shwactivity);
        shwstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shwstudActionPerformed(evt);
            }
        });

        shwactivity.setBackground(new java.awt.Color(255, 255, 255));
        shwactivity.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        shwactivity.setText("Click Here ");
        shwactivity.setNextFocusableComponent(shwstud);
        shwactivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shwactivityActionPerformed(evt);
            }
        });

        shwactivity1.setBackground(new java.awt.Color(255, 255, 255));
        shwactivity1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        shwactivity1.setText("Back");
        shwactivity1.setNextFocusableComponent(shwstud);
        shwactivity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shwactivity1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(254, 254, 254)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(275, 275, 275)
                                        .addComponent(studmg, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(204, 204, 204)
                                        .addComponent(shwstud, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(198, 198, 198))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nsmg1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nsmg2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nsmg3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(shwactivity, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(activmg, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(nsmg4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nsmg5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nsmg6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(585, 585, 585)
                        .addComponent(shwactivity1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(studmg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nsmg5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nsmg6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(activmg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nsmg4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(272, 272, 272)
                                    .addComponent(shwactivity, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nsmg3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nsmg2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nsmg1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(shwstud, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(shwactivity1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 830));

        assigntsk.setText("Assign Task ");
        assigntsk.setNextFocusableComponent(sendml);
        assigntsk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assigntskMouseClicked(evt);
            }
        });
        assigntsk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assigntskActionPerformed(evt);
            }
        });
        jMenuBar1.add(assigntsk);

        sendml.setText("Send Mail");
        sendml.setNextFocusableComponent(reportsrshow);
        sendml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendmlMouseClicked(evt);
            }
        });
        jMenuBar1.add(sendml);

        reportsrshow.setText("Reports");
        reportsrshow.setNextFocusableComponent(about);
        reportsrshow.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                reportsrshowMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        reportsrshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsrshowMouseClicked(evt);
            }
        });
        jMenuBar1.add(reportsrshow);

        about.setText("About");
        about.setNextFocusableComponent(shwstud);
        about.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                aboutMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("ABSA's NSS Management System 1.0 - Main Screen");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shwstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shwstudActionPerformed
        // TODO add your handling code here:
        Studinformation s1 =new Studinformation();
        s1.setVisible(true);
        dispose();
    }//GEN-LAST:event_shwstudActionPerformed

    private void shwactivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shwactivityActionPerformed
        // TODO add your handling code here
        Activities ac1=new Activities();
        ac1.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_shwactivityActionPerformed

    private void assigntskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assigntskActionPerformed

        
    }//GEN-LAST:event_assigntskActionPerformed

    private void assigntskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assigntskMouseClicked
        // TODO add your handling code here:
        AssignActivity assact1 = new AssignActivity();
        assact1.setVisible(true);
        dispose();
    }//GEN-LAST:event_assigntskMouseClicked

    private void sendmlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendmlMouseClicked
        // TODO add your handling code here:
        SendNotice s1=new SendNotice();
        s1.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_sendmlMouseClicked

    private void reportsrshowMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_reportsrshowMenuKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_reportsrshowMenuKeyPressed

    private void aboutMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_aboutMenuKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_aboutMenuKeyPressed

    private void reportsrshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsrshowMouseClicked
        // TODO add your handling code here:
        Reports r1=new Reports();
        r1.setVisible(true);
        dispose();
    }//GEN-LAST:event_reportsrshowMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        About ab1= new About();
        ab1.setVisible(true);
        dispose();
    }//GEN-LAST:event_aboutMouseClicked

    private void shwactivity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shwactivity1ActionPerformed
        // TODO add your handling code here:
        Loginform l1 = new Loginform();
        l1.setVisible(true);
        dispose();
    }//GEN-LAST:event_shwactivity1ActionPerformed
    
    void Exit()
        {
            int i = JOptionPane.showConfirmDialog(this, "Do You Want To Quit", "Quit", JOptionPane.YES_NO_OPTION);
            if(i==JOptionPane.YES_OPTION){
                 dispose();
            }
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/
      try{
            UIManager.setLookAndFeel(new TextureLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, ""+e);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainscreen().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JLabel activmg;
    private javax.swing.JMenu assigntsk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel nsmg1;
    private javax.swing.JLabel nsmg2;
    private javax.swing.JLabel nsmg3;
    private javax.swing.JLabel nsmg4;
    private javax.swing.JLabel nsmg5;
    private javax.swing.JLabel nsmg6;
    private javax.swing.JMenu reportsrshow;
    private javax.swing.JMenu sendml;
    private javax.swing.JButton shwactivity;
    private javax.swing.JButton shwactivity1;
    private javax.swing.JButton shwstud;
    private javax.swing.JLabel studmg;
    // End of variables declaration//GEN-END:variables
}
