import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.util.Properties;
import javax.mail.Session;
import javax.mail.Message;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LENOVO
 */
public class SendNotice extends javax.swing.JFrame {

    /**
     * Creates new form SendNotice
     */
    public SendNotice() {
        initComponents();
        ShowTabDta();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon myimg = new ImageIcon("C:\\Users\\LENOVO\\Desktop\\900px-NSS-symbol-removebg-preview.png");
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(nsslbl1.getWidth(), nsslbl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        nsslbl1.setIcon(scaledimg);
        nsslbl3.setIcon(scaledimg);
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\LENOVO\\Desktop\\final_icon_kZY_icon.png"));
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Exit();

            }

        });

    }

    void Exit() {
        int i = JOptionPane.showConfirmDialog(this, "Do You Want To Quit", "Quit", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            Mainscreen m1 = new Mainscreen();
            m1.setVisible(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nsslbl1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nsslbl3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subjectxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        backbtn = new javax.swing.JButton();
        Singlepane = new javax.swing.JPanel();
        singlstudbtn = new javax.swing.JButton();
        Singlepane1 = new javax.swing.JPanel();
        allstudsendbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dispdata = new javax.swing.JTable();
        Singlepane2 = new javax.swing.JPanel();
        gendstud = new javax.swing.JButton();
        Singlepane3 = new javax.swing.JPanel();
        nssunwise = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ABSA's NSS Management System 1.0 - Send Mail");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Send Notice's");

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel7.setText("Subject :");

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel8.setText("Text :");

        subjectxt.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        subjectxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        msg.setColumns(20);
        msg.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        msg.setRows(5);
        jScrollPane1.setViewportView(msg);

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        Singlepane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Single Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 12))); // NOI18N
        Singlepane.setOpaque(false);

        singlstudbtn.setBackground(new java.awt.Color(255, 255, 255));
        singlstudbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        singlstudbtn.setText("Click Here");
        singlstudbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlstudbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SinglepaneLayout = new javax.swing.GroupLayout(Singlepane);
        Singlepane.setLayout(SinglepaneLayout);
        SinglepaneLayout.setHorizontalGroup(
            SinglepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SinglepaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(singlstudbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        SinglepaneLayout.setVerticalGroup(
            SinglepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SinglepaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(singlstudbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Singlepane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "All Student's", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 12))); // NOI18N
        Singlepane1.setOpaque(false);

        allstudsendbtn.setBackground(new java.awt.Color(255, 255, 255));
        allstudsendbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        allstudsendbtn.setText("Click Here");
        allstudsendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allstudsendbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Singlepane1Layout = new javax.swing.GroupLayout(Singlepane1);
        Singlepane1.setLayout(Singlepane1Layout);
        Singlepane1Layout.setHorizontalGroup(
            Singlepane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Singlepane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allstudsendbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        Singlepane1Layout.setVerticalGroup(
            Singlepane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Singlepane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allstudsendbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "All Email Addresses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 12))); // NOI18N

        Dispdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Dispdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Dispdata);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        Singlepane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gender Wise", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 12))); // NOI18N
        Singlepane2.setOpaque(false);

        gendstud.setBackground(new java.awt.Color(255, 255, 255));
        gendstud.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        gendstud.setText("Click Here");
        gendstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendstudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Singlepane2Layout = new javax.swing.GroupLayout(Singlepane2);
        Singlepane2.setLayout(Singlepane2Layout);
        Singlepane2Layout.setHorizontalGroup(
            Singlepane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Singlepane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gendstud, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        Singlepane2Layout.setVerticalGroup(
            Singlepane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Singlepane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gendstud, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Singlepane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "NSS Unit Wise", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 12))); // NOI18N
        Singlepane3.setOpaque(false);

        nssunwise.setBackground(new java.awt.Color(255, 255, 255));
        nssunwise.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        nssunwise.setText("Click Here");
        nssunwise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nssunwiseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Singlepane3Layout = new javax.swing.GroupLayout(Singlepane3);
        Singlepane3.setLayout(Singlepane3Layout);
        Singlepane3Layout.setHorizontalGroup(
            Singlepane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Singlepane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nssunwise, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        Singlepane3Layout.setVerticalGroup(
            Singlepane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Singlepane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nssunwise, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(nsslbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(144, 144, 144))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subjectxt, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Singlepane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                        .addComponent(Singlepane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Singlepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Singlepane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nsslbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Singlepane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Singlepane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Singlepane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))))
                            .addComponent(Singlepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjectxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 860));

        getAccessibleContext().setAccessibleName("ABSA's NSS Management System 1.0 - Send Mail");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allstudsendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allstudsendbtnActionPerformed
        // TODO add your handling code here:
        int i = 0;
        if (subjectxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Subject Feild", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (msg.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Text Feild", "Error", JOptionPane.ERROR_MESSAGE);//
        } else {
            try {
                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                String query1 = "Select Email from Student";
                PreparedStatement pst = con1.prepareStatement(query1);
                ResultSet rs = pst.executeQuery();
                ArrayList<String> Studnm = new ArrayList<String>();
                while (rs.next()) {
                    String Temp = rs.getString(1);
                    Studnm.add(Temp);
                }
                //JOptionPane.showMessageDialog(this,Studnm.indexOf("abjain7218@gmail.com"));
                for (i = 0; i < Studnm.size(); i++) {
                    Sendmail(Studnm.get(i));
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_allstudsendbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        Mainscreen m1 = new Mainscreen();
        m1.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void singlstudbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlstudbtnActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog(this, "Enter The Number Of Student ");

        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select Email from Student where E_Id ='" + x + "'";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                int y = JOptionPane.showConfirmDialog(this, "Student Found Email Address Is\n" + rs.getString(1), "Send", JOptionPane.YES_NO_OPTION);
                if (y == JOptionPane.YES_OPTION) {
                    if (subjectxt.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Please Fill The Subject Feild", "Error", JOptionPane.ERROR_MESSAGE);//
                    } else if (msg.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Please Fill The Text Feild", "Error", JOptionPane.ERROR_MESSAGE);//
                    } else {
                        Sendmail(rs.getString(1));
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Student Dose Not Exist", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_singlstudbtnActionPerformed

    private void gendstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendstudActionPerformed
        // TODO add your handling code here:
        int i = 0;
        if (subjectxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Subject Feild", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (msg.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Text Feild", "Error", JOptionPane.ERROR_MESSAGE);//
        } else {
            String x = JOptionPane.showInputDialog(this, "Enter The Gender Of Student's\nMale/ Female / Others ");
            try {
                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                String query1 = "Select Email from Student where Gender  ='" + x + "'";
                PreparedStatement pst = con1.prepareStatement(query1);
                ResultSet rs = pst.executeQuery();
                ArrayList<String> Studnm = new ArrayList<String>();
                while (rs.next()) {
                        String Temp = rs.getString(1);
                        Studnm.add(Temp);
                    }
                    if(Studnm.isEmpty()){
                       JOptionPane.showMessageDialog(this, "Student Dose Not Exist", "Error", JOptionPane.ERROR_MESSAGE); 
                    }
                    else{
                    int y = JOptionPane.showConfirmDialog(this, "Students Found....Send Mail", "Send", JOptionPane.YES_NO_OPTION);
                    if (y == JOptionPane.YES_OPTION) {

                        for (i = 0; i < Studnm.size(); i++) {
                            Sendmail(Studnm.get(i));
                        }

                    }
            }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_gendstudActionPerformed

    private void nssunwiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nssunwiseActionPerformed
        // TODO add your handling code here:
       int i = 0;
        if (subjectxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Subject Feild", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (msg.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill The Text Feild", "Error", JOptionPane.ERROR_MESSAGE);//
        } else {
            String x = JOptionPane.showInputDialog(this, "Enter The NSS Unit Number Of Student's\n40130/40131");
            try {
                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                String query1 = "Select Email from Student where Nu_no='" + x + "'";
                PreparedStatement pst = con1.prepareStatement(query1);
                ResultSet rs = pst.executeQuery();
                ArrayList<String> Studnm = new ArrayList<String>();
                while (rs.next()) {
                        String Temp = rs.getString(1);
                        Studnm.add(Temp);
                    }
                    if(Studnm.isEmpty()){
                       JOptionPane.showMessageDialog(this, "Student Dose Not Exist", "Error", JOptionPane.ERROR_MESSAGE); 
                    }
                    else{
                    int y = JOptionPane.showConfirmDialog(this, "Students Found....Send Mail", "Send", JOptionPane.YES_NO_OPTION);
                    if (y == JOptionPane.YES_OPTION) {

                        for (i = 0; i < Studnm.size(); i++) {
                            Sendmail(Studnm.get(i));
                        }

                    }
            }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_nssunwiseActionPerformed

    public void ShowTabDta() {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select Email,Gender,Nu_no from Student";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            Dispdata.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void Sendmail(String Recp) {
        String To = Recp;
        String From = "nss.acacs@gmail.com";
        String EPass = "Arihant2020";

        Properties p = new Properties();
        p.put("mail.smtp.auth", "true");
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.put("mail.smtp.port", "587");

        Session s = Session.getDefaultInstance(p, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(From, EPass);
            }
        });
        try {
            MimeMessage m = new MimeMessage(s);
            m.setFrom(new InternetAddress(From));
            m.addRecipient(Message.RecipientType.TO, new InternetAddress(To));
            m.setSubject(subjectxt.getText());
            m.setText(msg.getText());
            Transport.send(m);
            JOptionPane.showMessageDialog(null, "Email sended To " + Recp + "");
        } catch (Exception e) {
            System.out.println("" + e);
            JOptionPane.showMessageDialog(null, "Something happened!\nCheck Internet Connection\nOr Verify Te Mail Address");
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/
        try {
            UIManager.setLookAndFeel(new TextureLookAndFeel());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendNotice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Dispdata;
    private javax.swing.JPanel Singlepane;
    private javax.swing.JPanel Singlepane1;
    private javax.swing.JPanel Singlepane2;
    private javax.swing.JPanel Singlepane3;
    private javax.swing.JButton allstudsendbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton gendstud;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea msg;
    private javax.swing.JLabel nsslbl1;
    private javax.swing.JLabel nsslbl3;
    private javax.swing.JButton nssunwise;
    private javax.swing.JButton singlstudbtn;
    private javax.swing.JTextField subjectxt;
    // End of variables declaration//GEN-END:variables
}
