
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.io.*;
import java.util.*;
import java.util.regex.Matcher;  
import java.util.regex.Pattern;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class Studinformation extends javax.swing.JFrame {

    /**
     * Creates new form Mainscreen
     */
    public Studinformation() {
        initComponents();
        ShowTabDta();
        AutoInc();
        addbtn.setEnabled(false);
        updtbtn.setEnabled(false);
        deltbtn.setEnabled(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon myimg = new ImageIcon("C:\\Users\\LENOVO\\Desktop\\900px-NSS-symbol-removebg-preview.png");
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(nsslbl1.getWidth(), nsslbl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        nsslbl1.setIcon(scaledimg);
        nsslbl3.setIcon(scaledimg);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Exit();

            }

        });
        
         setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\LENOVO\\Desktop\\final_icon_kZY_icon.png"));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog4 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog5 = new datechooser.beans.DateChooserDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        maleopt = new javax.swing.JRadioButton();
        femaleopt = new javax.swing.JRadioButton();
        othersopt = new javax.swing.JRadioButton();
        dob = new com.github.lgooddatepicker.components.DatePicker();
        classcombo = new javax.swing.JComboBox<>();
        nssunitcombo = new javax.swing.JComboBox<>();
        mobtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        adhdarlbl = new javax.swing.JLabel();
        heightlbl = new javax.swing.JLabel();
        weightlbl = new javax.swing.JLabel();
        guardilbl = new javax.swing.JLabel();
        addrlbl = new javax.swing.JLabel();
        pincodelbl = new javax.swing.JLabel();
        bloodlbl = new javax.swing.JLabel();
        blgrpcom = new javax.swing.JComboBox<>();
        aadhartxt = new javax.swing.JTextField();
        heighttxt = new javax.swing.JTextField();
        weighttxt = new javax.swing.JTextField();
        addrtxt = new javax.swing.JTextField();
        pincdtxt = new javax.swing.JTextField();
        guardtxt = new javax.swing.JTextField();
        nsslbl1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        adhdarlbl1 = new javax.swing.JLabel();
        studimg = new javax.swing.JLabel();
        imglodbtn = new javax.swing.JButton();
        imgloc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        deltbtn = new javax.swing.JButton();
        bckbtn = new javax.swing.JButton();
        rnotxt = new javax.swing.JTextField();
        nsslbl3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Displdta = new javax.swing.JTable();
        updtbtn = new javax.swing.JButton();
        bloodlbl1 = new javax.swing.JLabel();
        studyrtxt = new javax.swing.JTextField();
        verifbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        exportxls = new javax.swing.JButton();
        bloodlbl2 = new javax.swing.JLabel();
        bloodlbl3 = new javax.swing.JLabel();
        psd = new javax.swing.JPasswordField();
        confpsd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ABSA's NSS Management System 1.0 - Student Information");
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setNextFocusableComponent(nametxt);
        jPanel1.setOpaque(false);

        jLabel1.setText("Enrollment ID :");
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel2.setText("Name :");
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel3.setText("Gender :");
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel4.setText("Date Of Birth :");
        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel5.setText("Class :");
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel6.setText("NSS Unit No :");
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel7.setText("Mobile No :");
        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel8.setText("Email Address :");
        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        nametxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        nametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nametxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nametxt.setNextFocusableComponent(maleopt);
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        buttonGroup1.add(maleopt);
        maleopt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        maleopt.setText("Male");
        maleopt.setNextFocusableComponent(femaleopt);

        buttonGroup1.add(femaleopt);
        femaleopt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        femaleopt.setText("Female");
        femaleopt.setNextFocusableComponent(othersopt);
        femaleopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleoptActionPerformed(evt);
            }
        });

        buttonGroup1.add(othersopt);
        othersopt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        othersopt.setText("Others");
        othersopt.setNextFocusableComponent(dob);

        dob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dob.setNextFocusableComponent(mobtxt);

        classcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FY B.A", "FY B.Com", "FY BBA", "FY BCA", "SY B.A", "SY B.Com", "SY BBA", "SY BCA", "TY B.A", "TY B.Com", "TY BBA", "TY BCA" }));
        classcombo.setFocusable(false);
        classcombo.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        classcombo.setNextFocusableComponent(nssunitcombo);

        nssunitcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40130", "40131" }));
        nssunitcombo.setFocusable(false);
        nssunitcombo.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        nssunitcombo.setName(""); // NOI18N
        nssunitcombo.setNextFocusableComponent(mobtxt);

        mobtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        mobtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mobtxt.setNextFocusableComponent(emailtxt);

        emailtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        emailtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailtxt.setNextFocusableComponent(studyrtxt);

        adhdarlbl.setText("Aadhar Card No :");
        adhdarlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        heightlbl.setText("Height (cm) :");
        heightlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        weightlbl.setText("Weight (kg) :");
        weightlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        guardilbl.setText("Guardians Name :");
        guardilbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        addrlbl.setText("Address :");
        addrlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        pincodelbl.setText("Pincode :");
        pincodelbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        bloodlbl.setText("Blood Group :");
        bloodlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        blgrpcom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O-ve", "B-ve", "AB-ve", "A-ve", "A+ve", "AB+ve", "B+ve", "O+ve", " " }));
        blgrpcom.setFocusable(false);
        blgrpcom.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        blgrpcom.setNextFocusableComponent(psd);

        aadhartxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        aadhartxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        aadhartxt.setNextFocusableComponent(weighttxt);
        aadhartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadhartxtActionPerformed(evt);
            }
        });

        heighttxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        heighttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        heighttxt.setNextFocusableComponent(guardtxt);
        heighttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heighttxtActionPerformed(evt);
            }
        });

        weighttxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        weighttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        weighttxt.setNextFocusableComponent(heighttxt);
        weighttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weighttxtActionPerformed(evt);
            }
        });

        addrtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        addrtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addrtxt.setNextFocusableComponent(pincdtxt);
        addrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrtxtActionPerformed(evt);
            }
        });

        pincdtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        pincdtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pincdtxt.setNextFocusableComponent(blgrpcom);
        pincdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincdtxtActionPerformed(evt);
            }
        });

        guardtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        guardtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        guardtxt.setNextFocusableComponent(addrtxt);
        guardtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardtxtActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adhdarlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adhdarlbl1.setText("Image :");
        adhdarlbl1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        adhdarlbl1.setToolTipText("");
        jPanel2.add(adhdarlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 290, 44));

        studimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(studimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 194, 210));

        imglodbtn.setText("Load Picture");
        imglodbtn.setBackground(new java.awt.Color(255, 255, 255));
        imglodbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        imglodbtn.setNextFocusableComponent(verifbtn);
        imglodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imglodbtnActionPerformed(evt);
            }
        });
        jPanel2.add(imglodbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 296, 194, 43));

        imgloc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgloc.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        jPanel2.add(imgloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 194, 19));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Student Information ");
        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N

        addbtn.setText("Add Details");
        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        addbtn.setNextFocusableComponent(updtbtn);
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        deltbtn.setText("Delete");
        deltbtn.setBackground(new java.awt.Color(255, 255, 255));
        deltbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        deltbtn.setNextFocusableComponent(searchbtn);
        deltbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltbtnActionPerformed(evt);
            }
        });

        bckbtn.setText("Back");
        bckbtn.setBackground(new java.awt.Color(255, 255, 255));
        bckbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        bckbtn.setNextFocusableComponent(nametxt);
        bckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckbtnActionPerformed(evt);
            }
        });

        rnotxt.setEditable(false);
        rnotxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        rnotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rnotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnotxtActionPerformed(evt);
            }
        });
        rnotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rnotxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rnotxtKeyTyped(evt);
            }
        });

        Displdta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Displdta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Displdta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DispldtaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Displdta);

        updtbtn.setText("Update");
        updtbtn.setBackground(new java.awt.Color(255, 255, 255));
        updtbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        updtbtn.setNextFocusableComponent(deltbtn);
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });

        bloodlbl1.setText("Admission Year :");
        bloodlbl1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        studyrtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        studyrtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        studyrtxt.setNextFocusableComponent(aadhartxt);
        studyrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyrtxtActionPerformed(evt);
            }
        });

        verifbtn.setText("Verify");
        verifbtn.setBackground(new java.awt.Color(255, 255, 255));
        verifbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        verifbtn.setNextFocusableComponent(addbtn);
        verifbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifbtnActionPerformed(evt);
            }
        });

        searchbtn.setText("Search");
        searchbtn.setBackground(new java.awt.Color(255, 255, 255));
        searchbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        searchbtn.setNextFocusableComponent(exportxls);
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        exportxls.setText("Excel");
        exportxls.setBackground(new java.awt.Color(255, 255, 255));
        exportxls.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        exportxls.setNextFocusableComponent(bckbtn);
        exportxls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportxlsActionPerformed(evt);
            }
        });

        bloodlbl2.setText("Password :");
        bloodlbl2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        bloodlbl3.setText("Confirm Password :");
        bloodlbl3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        psd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        psd.setNextFocusableComponent(confpsd);

        confpsd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confpsd.setNextFocusableComponent(imglodbtn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nsslbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bloodlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(studyrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(bloodlbl3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(maleopt)
                                        .addGap(15, 15, 15)
                                        .addComponent(femaleopt)
                                        .addGap(15, 15, 15)
                                        .addComponent(othersopt))
                                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(classcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nssunitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adhdarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(heightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pincodelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(aadhartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(weighttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(heighttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(guardtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(addrtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(pincdtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(blgrpcom, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psd)
                                    .addComponent(confpsd, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(47, 47, 47)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(updtbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(verifbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deltbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exportxls, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 52, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nsslbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maleopt)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(femaleopt)
                                .addComponent(othersopt)))
                        .addGap(27, 27, 27)
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(classcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(nssunitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(mobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(adhdarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(weightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(heightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(guardilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(addrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(pincodelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blgrpcom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(aadhartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(weighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(heighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(guardtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(addrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(pincdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verifbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(deltbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studyrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(confpsd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bloodlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exportxls, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        jLabel10.getAccessibleContext().setAccessibleName("                                                        Student Information ");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, -1));

        getAccessibleContext().setAccessibleName("ABSA's NSS Management System 1.0 - Student Information");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rnotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnotxtActionPerformed

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        // TODO add your handling code here:
        Mainscreen m1 = new Mainscreen();
        m1.setVisible(true);
        dispose();
    }//GEN-LAST:event_bckbtnActionPerformed

    private void deltbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltbtnActionPerformed
        // TODO add your handling code here:
        String Delq;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            Delq = "delete from Student where E_Id='" + rnotxt.getText() + "'";
            PreparedStatement delptstmt = con.prepareStatement(Delq);
            //delptstmt.setInt(1,Integer.parseInt());
            delptstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Deleted Record Successfully From Database Database");
            con.close();
            addbtn.setEnabled(false);
            updtbtn.setEnabled(false);
            deltbtn.setEnabled(false);
            clear();
            ShowTabDta();
            AutoInc();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_deltbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String insq, gend = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String insq2 = "select E_Id from Student where E_Id='" + rnotxt.getText() + "'";

            PreparedStatement ptstmt2 = con2.prepareStatement(insq2);
            ResultSet rs2 = ptstmt2.executeQuery();

            if (!rs2.next()) {

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                insq = "insert into Student values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement ptstmt = con.prepareStatement(insq);
                //To Add Items Into Database
                ptstmt.setInt(1, Integer.parseInt(rnotxt.getText()));
                ptstmt.setString(2, nametxt.getText());
                if (maleopt.isSelected()) {
                    gend = maleopt.getText();

                }
                if (femaleopt.isSelected()) {
                    gend = femaleopt.getText();

                }
                if (othersopt.isSelected()) {
                    gend = othersopt.getText();
                }
                ptstmt.setString(3, gend);
                ptstmt.setString(4, dob.getText());
                ptstmt.setString(5, classcombo.getSelectedItem().toString());
                ptstmt.setString(6, nssunitcombo.getSelectedItem().toString());
                ptstmt.setString(7, mobtxt.getText());
                ptstmt.setString(8, emailtxt.getText());
                ptstmt.setString(9, aadhartxt.getText());
                ptstmt.setString(10, weighttxt.getText());
                ptstmt.setString(11, heighttxt.getText());
                ptstmt.setString(12, guardtxt.getText());
                ptstmt.setString(13, addrtxt.getText());
                ptstmt.setString(14, pincdtxt.getText());
                ptstmt.setString(15, imgloc.getText());
                ptstmt.setString(16, blgrpcom.getSelectedItem().toString());
                ptstmt.setString(17, studyrtxt.getText());
                ptstmt.setString(18, psd.getText());
                ptstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Inserted Successfully Into Database");
                con.close();
                clear();
                addbtn.setEnabled(false);
                updtbtn.setEnabled(false);
                deltbtn.setEnabled(false);

                AutoInc();
                ShowTabDta();

            } else {
                JOptionPane.showMessageDialog(this, "Student Already Exist Either Click On Update\nOr On Delete Button", "Error", JOptionPane.ERROR_MESSAGE);
            }
            ptstmt2.close();
            con2.close();

            // Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void imglodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imglodbtnActionPerformed
        // TODO add your handling code here:
        //To Load Image 
        String loc;
        JFileChooser imgch = new JFileChooser();
        imgch.showOpenDialog(null);
        File f = imgch.getSelectedFile();
        loc = f.getAbsolutePath();
        imgloc.setText(loc);
        ImageIcon myimg = new ImageIcon(loc);
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(studimg.getWidth(), studimg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        studimg.setIcon(scaledimg);

    }//GEN-LAST:event_imglodbtnActionPerformed

    private void guardtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardtxtActionPerformed

    private void pincdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pincdtxtActionPerformed

    private void addrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrtxtActionPerformed

    private void weighttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weighttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weighttxtActionPerformed

    private void heighttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heighttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heighttxtActionPerformed

    private void aadhartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadhartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadhartxtActionPerformed

    private void femaleoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleoptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleoptActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
        // TODO add your handling code here:
        String Upsql, gend = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            Upsql = "Update Student Set S_Name=?,Gender=?,DOB=?,Class=?,Nu_no=?,Ph_no=?,Email=?,Adh_no=?,Weight=?,Height=?,Par_nm=?,Addr=?,Pinc=?,Image=?,blgrp=?,S_year=?,Pass=? where E_Id=?";
            PreparedStatement ptstmt = con.prepareStatement(Upsql);
            ptstmt.setInt(18, Integer.parseInt(rnotxt.getText()));
            ptstmt.setString(1, nametxt.getText());
            if (maleopt.isSelected()) {
                gend = maleopt.getText();

            }
            if (femaleopt.isSelected()) {
                gend = femaleopt.getText();

            }
            if (othersopt.isSelected()) {
                gend = othersopt.getText();
            }
            ptstmt.setString(2, gend);
            ptstmt.setString(3, dob.getText());
            ptstmt.setString(4, classcombo.getSelectedItem().toString());
            ptstmt.setString(5, nssunitcombo.getSelectedItem().toString());
            ptstmt.setString(6, mobtxt.getText());
            ptstmt.setString(7, emailtxt.getText());
            ptstmt.setString(8, aadhartxt.getText());
            ptstmt.setString(9, weighttxt.getText());
            ptstmt.setString(10, heighttxt.getText());
            ptstmt.setString(11, guardtxt.getText());
            ptstmt.setString(12, addrtxt.getText());
            ptstmt.setString(13, pincdtxt.getText());
            ptstmt.setString(14, imgloc.getText());
            ptstmt.setString(15, blgrpcom.getSelectedItem().toString());
            ptstmt.setString(16, studyrtxt.getText());
            ptstmt.setString(17, psd.getText());
            ptstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Updated Details Successfully Into Database");
            addbtn.setEnabled(false);
            updtbtn.setEnabled(false);
            deltbtn.setEnabled(false);

            clear();
            ShowTabDta();
            AutoInc();

        } catch (Exception e) {
            System.out.println("" + e);
        }
    }//GEN-LAST:event_updtbtnActionPerformed

    private void DispldtaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DispldtaMouseClicked
        // TODO add your handling code here:
        addbtn.setEnabled(false);

        int i = Displdta.getSelectedRow();
        TableModel M1 = Displdta.getModel();
        rnotxt.setText(M1.getValueAt(i, 0).toString());
        nametxt.setText(M1.getValueAt(i, 1).toString());
        if (M1.getValueAt(i, 2).toString().equals(maleopt.getText())) {
            maleopt.setSelected(true);

        }
        if (M1.getValueAt(i, 2).toString().equals(femaleopt.getText())) {
            femaleopt.setSelected(true);

        }
        if (M1.getValueAt(i, 2).toString().equals(othersopt.getText())) {
            othersopt.setSelected(true);

        }

        dob.setText(M1.getValueAt(i, 3).toString());
        classcombo.setSelectedItem(M1.getValueAt(i, 4).toString());
        nssunitcombo.setSelectedItem(M1.getValueAt(i, 5).toString());
        mobtxt.setText(M1.getValueAt(i, 6).toString());
        emailtxt.setText(M1.getValueAt(i, 7).toString());
        aadhartxt.setText(M1.getValueAt(i, 8).toString());
        weighttxt.setText(M1.getValueAt(i, 9).toString());
        heighttxt.setText(M1.getValueAt(i, 10).toString());
        guardtxt.setText(M1.getValueAt(i, 11).toString());
        addrtxt.setText(M1.getValueAt(i, 12).toString());
        pincdtxt.setText(M1.getValueAt(i, 13).toString());
        blgrpcom.setSelectedItem(M1.getValueAt(i, 15).toString());
        imgloc.setText(M1.getValueAt(i, 14).toString());
        studyrtxt.setText(M1.getValueAt(i, 16).toString());
        psd.setText(M1.getValueAt(i, 17).toString());
        confpsd.setText(psd.getText());
        ImageIcon myimg = new ImageIcon(imgloc.getText());
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(studimg.getWidth(), studimg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        studimg.setIcon(scaledimg);


    }//GEN-LAST:event_DispldtaMouseClicked

    private void studyrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studyrtxtActionPerformed

    private void rnotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rnotxtKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_rnotxtKeyPressed

    private void rnotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rnotxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_rnotxtKeyTyped

    private void verifbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifbtnActionPerformed
        // TODO add your handling code here:

        if (!(Pattern.matches("^[a-zA-Z]{1,20}[ ]{0,1}[a-zA-Z]{0,20}$", nametxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Name", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (dob.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Date Field Is Blank", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (classcombo.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Class Field Is Not Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (nssunitcombo.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "NSS Unit Field Is Not Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[7-9][0-9]{9}$", mobtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Phone Number", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[a-zA-Z.0-9]+[@]{1}+[a-zA-Z]+[.]{1}+[com]+$", emailtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Email Address", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]{12}$", aadhartxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Adhar Number", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]{0,3}$", weighttxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Weight", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (!(Pattern.matches("^[0-9]{0,3}$", heighttxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Height ", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (!(Pattern.matches("^[A-Za-z]{1,20}[ ]{0,1}[A-Za-z]{0,20}$", guardtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Guardians", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (addrtxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Address Field Is Blank", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]{6}$", pincdtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Pin-code", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (blgrpcom.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Blood Group Field Is Not Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (imgloc.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Image Field Is Not Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[2][0][0-9]{2}$", studyrtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Student Year", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (psd.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Password Field Is Empty", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (!psd.getText().equals(confpsd.getText())) {
            JOptionPane.showMessageDialog(this, "Password Dose Not Match", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Verified");
            addbtn.setEnabled(true);
            updtbtn.setEnabled(true);
            deltbtn.setEnabled(true);

        }


    }//GEN-LAST:event_verifbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        clear();
        String nm = JOptionPane.showInputDialog(this, "Enter The Enrollment ID Of Student");

        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select * from Student where E_Id='" + nm + "'";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {

                rnotxt.setText(rs.getString(1));
                nametxt.setText(rs.getString(2));
                if (rs.getString(3).equals(maleopt.getText())) {
                    maleopt.setSelected(true);

                }
                if (rs.getString(3).equals(femaleopt.getText())) {
                    femaleopt.setSelected(true);

                }
                if (rs.getString(3).equals(othersopt.getText())) {
                    othersopt.setSelected(true);

                }

                dob.setText(rs.getString(4));
                classcombo.setSelectedItem(rs.getString(5));
                nssunitcombo.setSelectedItem(rs.getString(6));
                mobtxt.setText(rs.getString(7));
                emailtxt.setText(rs.getString(8));
                aadhartxt.setText(rs.getString(9));
                weighttxt.setText(rs.getString(10));
                heighttxt.setText(rs.getString(11));
                guardtxt.setText(rs.getString(12));
                addrtxt.setText(rs.getString(13));
                pincdtxt.setText(rs.getString(14));
                imgloc.setText(rs.getString(15));
                blgrpcom.setSelectedItem(rs.getString(16));
                studyrtxt.setText(rs.getString(17));
                psd.setText(rs.getString(18));
                confpsd.setText(psd.getText());
                ImageIcon myimg = new ImageIcon(imgloc.getText());
                Image img1 = myimg.getImage();
                Image img2 = img1.getScaledInstance(studimg.getWidth(), studimg.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledimg = new ImageIcon(img2);
                studimg.setIcon(scaledimg);

            } else {

                JOptionPane.showMessageDialog(this, "Student Is Not Enrolled", "Error", JOptionPane.ERROR_MESSAGE);//

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_searchbtnActionPerformed

    private void exportxlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportxlsActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\LENOVO\\Desktop\\Exported Files";
        JFileChooser ExcelExport = new JFileChooser(path);
        int excelChooser = ExcelExport.showSaveDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {

            XSSFWorkbook wb = new XSSFWorkbook();
            XSSFSheet ws = wb.createSheet("Student Details");

            for (int i = 0; i < Displdta.getRowCount(); i++) {

                XSSFRow r = ws.createRow(i);

                for (int j = 0; j < Displdta.getColumnCount(); j++) {

                    XSSFCell c = r.createCell(j);

                    c.setCellValue(Displdta.getValueAt(i, j).toString());
                }
            }
            FileOutputStream exclfile;
            BufferedOutputStream excelbu;
            try {
                exclfile = new FileOutputStream(ExcelExport.getSelectedFile() + ".xlsx");

                excelbu = new BufferedOutputStream(exclfile);
                wb.write(excelbu);
                excelbu.close();
                wb.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }

    }//GEN-LAST:event_exportxlsActionPerformed
    public void AutoInc() {
        String selc = "select Max(E_Id) from Student";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement selpst = con.prepareStatement(selc);
            ResultSet rs = selpst.executeQuery();
            if (rs.next()) {
                int auto = rs.getInt(1);
                int autoin = auto + 1;
                rnotxt.setText(Integer.toString(autoin));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    public void clear() {
        rnotxt.setText("");
        nametxt.setText("");
        femaleopt.setSelected(false);
        maleopt.setSelected(false);
        othersopt.setSelected(false);
        dob.setText("");
        classcombo.setSelectedItem("");
        nssunitcombo.setSelectedItem("");
        mobtxt.setText("");
        emailtxt.setText("");
        aadhartxt.setText("");
        weighttxt.setText("");
        heighttxt.setText("");
        guardtxt.setText("");
        addrtxt.setText("");
        pincdtxt.setText("");
        blgrpcom.setSelectedItem("");
        imgloc.setText("");
        studyrtxt.setText("");
        studimg.setIcon(null);
        psd.setText("");
        confpsd.setText("");
    }

    public void ShowTabDta() {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select * from Student";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            Displdta.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    void Exit() {
        int i = JOptionPane.showConfirmDialog(this, "Do You Want To Quit", "Quit", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            Mainscreen m1 = new Mainscreen();
            m1.setVisible(true);
            dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>*/
        try {
            UIManager.setLookAndFeel(new TextureLookAndFeel());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studinformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Displdta;
    private javax.swing.JTextField aadhartxt;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel addrlbl;
    private javax.swing.JTextField addrtxt;
    private javax.swing.JLabel adhdarlbl;
    private javax.swing.JLabel adhdarlbl1;
    private javax.swing.JButton bckbtn;
    private javax.swing.JComboBox<String> blgrpcom;
    private javax.swing.JLabel bloodlbl;
    private javax.swing.JLabel bloodlbl1;
    private javax.swing.JLabel bloodlbl2;
    private javax.swing.JLabel bloodlbl3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> classcombo;
    private javax.swing.JPasswordField confpsd;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private datechooser.beans.DateChooserDialog dateChooserDialog4;
    private datechooser.beans.DateChooserDialog dateChooserDialog5;
    private javax.swing.JButton deltbtn;
    private com.github.lgooddatepicker.components.DatePicker dob;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JButton exportxls;
    private javax.swing.JRadioButton femaleopt;
    private javax.swing.JLabel guardilbl;
    private javax.swing.JTextField guardtxt;
    private javax.swing.JLabel heightlbl;
    private javax.swing.JTextField heighttxt;
    private javax.swing.JLabel imgloc;
    private javax.swing.JButton imglodbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleopt;
    private javax.swing.JTextField mobtxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel nsslbl1;
    private javax.swing.JLabel nsslbl3;
    private javax.swing.JComboBox<String> nssunitcombo;
    private javax.swing.JRadioButton othersopt;
    private javax.swing.JTextField pincdtxt;
    private javax.swing.JLabel pincodelbl;
    private javax.swing.JPasswordField psd;
    private javax.swing.JTextField rnotxt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLabel studimg;
    private javax.swing.JTextField studyrtxt;
    private javax.swing.JButton updtbtn;
    private javax.swing.JButton verifbtn;
    private javax.swing.JLabel weightlbl;
    private javax.swing.JTextField weighttxt;
    // End of variables declaration//GEN-END:variables
}
