
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.io.*;
import java.util.*;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

public class studview extends javax.swing.JFrame {

    /**
     * Creates new form Mainscreen
     */
    public studview() {
        initComponents();
        updtbtn.setEnabled(false);
        rnotxt.setEnabled(false);
        nametxt.setEnabled(false);
        femaleopt.setEnabled(false);
        maleopt.setEnabled(false);
        othersopt.setEnabled(false);
        dob.setEnabled(false);
        classcombo.setEnabled(false);
        nssunitcombo.setEnabled(false);
        mobtxt.setEnabled(false);
        emailtxt.setEnabled(false);
        aadhartxt.setEnabled(false);
        weighttxt.setEnabled(false);
        heighttxt.setEnabled(false);
        guardtxt.setEnabled(false);
        addrtxt.setEnabled(false);
        pincdtxt.setEnabled(false);
        blgrpcom.setEnabled(false);
        imgloc.setEnabled(false);
        studyrtxt.setEnabled(false);
        psd.setEnabled(false);
        confpsd.setEnabled(false);
        studimg.setEnabled(false);

        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\LENOVO\\Desktop\\final_icon_kZY_icon.png"));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon myimg = new ImageIcon("C:\\Users\\LENOVO\\Desktop\\900px-NSS-symbol-removebg-preview.png");
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(nsslbl1.getWidth(), nsslbl1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        nsslbl1.setIcon(scaledimg);
        nsslbl3.setIcon(scaledimg);

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Exit();

            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog4 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog5 = new datechooser.beans.DateChooserDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        maleopt = new javax.swing.JRadioButton();
        femaleopt = new javax.swing.JRadioButton();
        othersopt = new javax.swing.JRadioButton();
        dob = new com.github.lgooddatepicker.components.DatePicker();
        classcombo = new javax.swing.JComboBox<>();
        nssunitcombo = new javax.swing.JComboBox<>();
        mobtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        adhdarlbl = new javax.swing.JLabel();
        heightlbl = new javax.swing.JLabel();
        weightlbl = new javax.swing.JLabel();
        guardilbl = new javax.swing.JLabel();
        addrlbl = new javax.swing.JLabel();
        pincodelbl = new javax.swing.JLabel();
        bloodlbl = new javax.swing.JLabel();
        blgrpcom = new javax.swing.JComboBox<>();
        aadhartxt = new javax.swing.JTextField();
        heighttxt = new javax.swing.JTextField();
        weighttxt = new javax.swing.JTextField();
        addrtxt = new javax.swing.JTextField();
        pincdtxt = new javax.swing.JTextField();
        guardtxt = new javax.swing.JTextField();
        nsslbl1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        adhdarlbl1 = new javax.swing.JLabel();
        studimg = new javax.swing.JLabel();
        imglodbtn = new javax.swing.JButton();
        imgloc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bckbtn = new javax.swing.JButton();
        rnotxt = new javax.swing.JTextField();
        nsslbl3 = new javax.swing.JLabel();
        updtbtn = new javax.swing.JButton();
        bloodlbl1 = new javax.swing.JLabel();
        studyrtxt = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        bloodlbl2 = new javax.swing.JLabel();
        bloodlbl3 = new javax.swing.JLabel();
        psd = new javax.swing.JPasswordField();
        confpsd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ABSA's NSS Management System 1.0 - Student Update");
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);

        jLabel1.setText("Enrollment ID :");
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel2.setText("Name :");
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel3.setText("Gender :");
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel4.setText("Date Of Birth :");
        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel5.setText("Class :");
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel6.setText("NSS Unit No :");
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel7.setText("Mobile No :");
        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        jLabel8.setText("Email Address :");
        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        nametxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        nametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        buttonGroup1.add(maleopt);
        maleopt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        maleopt.setText("Male");

        buttonGroup1.add(femaleopt);
        femaleopt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        femaleopt.setText("Female");
        femaleopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleoptActionPerformed(evt);
            }
        });

        buttonGroup1.add(othersopt);
        othersopt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        othersopt.setText("Others");

        dob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FY B.A", "FY B.Com", "FY BBA", "FY BCA", "SY B.A", "SY B.Com", "SY BBA", "SY BCA", "TY B.A", "TY B.Com", "TY BBA", "TY BCA" }));
        classcombo.setFocusable(false);
        classcombo.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N

        nssunitcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40128", "40129", "40130", "40131" }));
        nssunitcombo.setFocusable(false);
        nssunitcombo.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        nssunitcombo.setName(""); // NOI18N

        mobtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        mobtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        emailtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        emailtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        adhdarlbl.setText("Aadhar Card No :");
        adhdarlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        heightlbl.setText("Height (cm) :");
        heightlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        weightlbl.setText("Weight (kg) :");
        weightlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        guardilbl.setText("Guardians Name :");
        guardilbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        addrlbl.setText("Address :");
        addrlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        pincodelbl.setText("Pincode :");
        pincodelbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        bloodlbl.setText("Blood Group :");
        bloodlbl.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        blgrpcom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O-ve", "B-ve", "AB-ve", "A-ve", "A+ve", "AB+ve", "B+ve", "O+ve", " " }));
        blgrpcom.setFocusable(false);
        blgrpcom.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N

        aadhartxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        aadhartxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        aadhartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadhartxtActionPerformed(evt);
            }
        });

        heighttxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        heighttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        heighttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heighttxtActionPerformed(evt);
            }
        });

        weighttxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        weighttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        weighttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weighttxtActionPerformed(evt);
            }
        });

        addrtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        addrtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrtxtActionPerformed(evt);
            }
        });

        pincdtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        pincdtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pincdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincdtxtActionPerformed(evt);
            }
        });

        guardtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        guardtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        guardtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardtxtActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adhdarlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adhdarlbl1.setText("Image :");
        adhdarlbl1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        adhdarlbl1.setToolTipText("");
        jPanel2.add(adhdarlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 290, 44));

        studimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(studimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 194, 210));

        imglodbtn.setText("Load Picture");
        imglodbtn.setBackground(new java.awt.Color(255, 255, 255));
        imglodbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        imglodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imglodbtnActionPerformed(evt);
            }
        });
        jPanel2.add(imglodbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 296, 194, 43));

        imgloc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgloc.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        jPanel2.add(imgloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 194, 19));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Update Student");
        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N

        bckbtn.setText("Back");
        bckbtn.setBackground(new java.awt.Color(255, 255, 255));
        bckbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bckbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        bckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckbtnActionPerformed(evt);
            }
        });

        rnotxt.setEditable(false);
        rnotxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        rnotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rnotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnotxtActionPerformed(evt);
            }
        });
        rnotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rnotxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rnotxtKeyTyped(evt);
            }
        });

        updtbtn.setText("Update");
        updtbtn.setBackground(new java.awt.Color(255, 255, 255));
        updtbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updtbtn.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });

        bloodlbl1.setText("Admission Year :");
        bloodlbl1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        studyrtxt.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        studyrtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        studyrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyrtxtActionPerformed(evt);
            }
        });

        login.setText("Login");
        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        bloodlbl2.setText("Password :");
        bloodlbl2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        bloodlbl3.setText("Confirm Password :");
        bloodlbl3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N

        psd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        confpsd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nsslbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(458, 458, 458))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bloodlbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(maleopt)
                                        .addGap(15, 15, 15)
                                        .addComponent(femaleopt)
                                        .addGap(15, 15, 15)
                                        .addComponent(othersopt))
                                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(classcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nssunitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studyrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adhdarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(heightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guardilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pincodelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(152, 152, 152)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(aadhartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(weighttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(heighttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(guardtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(addrtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(pincdtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(blgrpcom, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psd)
                                    .addComponent(confpsd))
                                .addGap(76, 76, 76)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nsslbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(nsslbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(adhdarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(weightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(heightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(guardilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(addrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(pincodelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bloodlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blgrpcom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maleopt)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(femaleopt)
                                        .addComponent(othersopt)))
                                .addGap(27, 27, 27)
                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(classcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(nssunitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(mobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(aadhartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(weighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(heighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(guardtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(addrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(pincdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(psd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bloodlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studyrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bloodlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(confpsd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jLabel10.getAccessibleContext().setAccessibleName("                                                        Student Information ");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 870));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rnotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnotxtActionPerformed

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        // TODO add your handling code here:
        Optionform o1 = new Optionform();
        o1.setVisible(true);
        dispose();
    }//GEN-LAST:event_bckbtnActionPerformed

    private void imglodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imglodbtnActionPerformed
        // TODO add your handling code here:
        //To Load Image 
        String loc;
        JFileChooser imgch = new JFileChooser();
        imgch.showOpenDialog(null);
        File f = imgch.getSelectedFile();
        loc = f.getAbsolutePath();
        imgloc.setText(loc);
        ImageIcon myimg = new ImageIcon(loc);
        Image img1 = myimg.getImage();
        Image img2 = img1.getScaledInstance(studimg.getWidth(), studimg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimg = new ImageIcon(img2);
        studimg.setIcon(scaledimg);

    }//GEN-LAST:event_imglodbtnActionPerformed

    private void guardtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardtxtActionPerformed

    private void pincdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pincdtxtActionPerformed

    private void addrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrtxtActionPerformed

    private void weighttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weighttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weighttxtActionPerformed

    private void heighttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heighttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heighttxtActionPerformed

    private void aadhartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadhartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadhartxtActionPerformed

    private void femaleoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleoptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleoptActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
        // TODO add your handling code here:
        String Upsql, gend = null;
        if (!(Pattern.matches("^[a-zA-Z]{1,20}[ ]{0,1}[a-zA-Z]{0,20}$", nametxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Name", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (dob.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Date Field Is Blank", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (classcombo.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Class Field Is Not Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (nssunitcombo.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "NSS Unit Field Is Not Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[7-9][0-9]{9}$", mobtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Phone Number", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[a-zA-Z.0-9]+[@]{1}+[a-zA-Z]+[.]{1}+[com]+$", emailtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Email Address", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]{12}$", aadhartxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Adhar Number", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]{0,3}$", weighttxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Weight", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (!(Pattern.matches("^[0-9]{0,3}$", heighttxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Height ", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (!(Pattern.matches("^[A-Za-z]{1,20}[ ]{0,1}[A-Za-z]{0,20}$", guardtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Guardians", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (addrtxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Address Field Is Blank", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[0-9]{6}$", pincdtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Pin-code", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (blgrpcom.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Blood Group Field Is Not Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (imgloc.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Image Field Is Not Selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Pattern.matches("^[2][0][0-9]{2}$", studyrtxt.getText()))) {
            JOptionPane.showMessageDialog(this, "Invalid Student Year", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (psd.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Password Field Is Empty", "Error", JOptionPane.ERROR_MESSAGE);//
        } else if (!psd.getText().equals(confpsd.getText())) {
            JOptionPane.showMessageDialog(this, "Password Dose Not Match", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                Upsql = "Update Student Set S_Name=?,Gender=?,DOB=?,Class=?,Nu_no=?,Ph_no=?,Email=?,Adh_no=?,Weight=?,Height=?,Par_nm=?,Addr=?,Pinc=?,Image=?,blgrp=?,S_year=?,Pass=? where E_Id=?";
                PreparedStatement ptstmt = con.prepareStatement(Upsql);
                ptstmt.setInt(18, Integer.parseInt(rnotxt.getText()));
                ptstmt.setString(1, nametxt.getText());
                if (maleopt.isSelected()) {
                    gend = maleopt.getText();

                }
                if (femaleopt.isSelected()) {
                    gend = femaleopt.getText();

                }
                if (othersopt.isSelected()) {
                    gend = othersopt.getText();
                }
                ptstmt.setString(2, gend);
                ptstmt.setString(3, dob.getText());
                ptstmt.setString(4, classcombo.getSelectedItem().toString());
                ptstmt.setString(5, nssunitcombo.getSelectedItem().toString());
                ptstmt.setString(6, mobtxt.getText());
                ptstmt.setString(7, emailtxt.getText());
                ptstmt.setString(8, aadhartxt.getText());
                ptstmt.setString(9, weighttxt.getText());
                ptstmt.setString(10, heighttxt.getText());
                ptstmt.setString(11, guardtxt.getText());
                ptstmt.setString(12, addrtxt.getText());
                ptstmt.setString(13, pincdtxt.getText());
                ptstmt.setString(14, imgloc.getText());
                ptstmt.setString(15, blgrpcom.getSelectedItem().toString());
                ptstmt.setString(16, studyrtxt.getText());
                ptstmt.setString(17, psd.getText());
                ptstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Updated Details Successfully Into Database");

                clr();

            } catch (Exception e) {
                System.out.println("" + e);
            }
        }
        updtbtn.setEnabled(false);
        rnotxt.setEnabled(false);
        nametxt.setEnabled(false);
        femaleopt.setEnabled(false);
        maleopt.setEnabled(false);
        othersopt.setEnabled(false);
        dob.setEnabled(false);
        classcombo.setEnabled(false);
        nssunitcombo.setEnabled(false);
        mobtxt.setEnabled(false);
        emailtxt.setEnabled(false);
        aadhartxt.setEnabled(false);
        weighttxt.setEnabled(false);
        heighttxt.setEnabled(false);
        guardtxt.setEnabled(false);
        addrtxt.setEnabled(false);
        pincdtxt.setEnabled(false);
        blgrpcom.setEnabled(false);
        imgloc.setEnabled(false);
        studyrtxt.setEnabled(false);
        psd.setEnabled(false);
        confpsd.setEnabled(false);
        studimg.setEnabled(false);
        updtbtn.setEnabled(false);
    }//GEN-LAST:event_updtbtnActionPerformed

    private void studyrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studyrtxtActionPerformed

    private void rnotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rnotxtKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_rnotxtKeyPressed

    private void rnotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rnotxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_rnotxtKeyTyped

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        clr();
        String Studid = JOptionPane.showInputDialog(this, "Enter Student ID");
        String qry = "Select E_Id, Pass from Student where E_Id ='" + Studid + "'";
        String qry1 = "Select Email,Pass from Student where E_id='" + Studid + "'";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            PreparedStatement ps = con.prepareStatement(qry);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String Pwd = JOptionPane.showInputDialog(this, "Enter Student Password");
                String dbpsd = rs.getString(2);
                String entpsd = Pwd;
                if (dbpsd.equals(entpsd)) {
                    selestud(Studid, Pwd);

                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Password", "Error", JOptionPane.ERROR_MESSAGE);
                    int i = JOptionPane.showConfirmDialog(this, "Click Here For Fergot Password");
                    if (i == 0) {
                        Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
                        PreparedStatement ps2 = con2.prepareStatement(qry1);
                        ResultSet rs2 = ps2.executeQuery();
                        if (rs2.next()) {
                            sendmail(rs2.getString(1), rs2.getString(2));

                        }

                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Student Is Not Enrolled", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_loginActionPerformed

    public void clr() {
        rnotxt.setText("");
        nametxt.setText("");
        femaleopt.setSelected(false);
        maleopt.setSelected(false);
        othersopt.setSelected(false);
        dob.setText("");
        classcombo.setSelectedItem("");
        nssunitcombo.setSelectedItem("");
        mobtxt.setText("");
        emailtxt.setText("");
        aadhartxt.setText("");
        weighttxt.setText("");
        heighttxt.setText("");
        guardtxt.setText("");
        addrtxt.setText("");
        pincdtxt.setText("");
        blgrpcom.setSelectedItem("");
        imgloc.setText("");
        studyrtxt.setText("");
        psd.setText("");
        confpsd.setText("");
        studimg.setIcon(null);

    }

    public static void sendmail(String R, String Pass) {

        try {
            JOptionPane.showMessageDialog(null, "Preparing To Send Mail");
            Properties p = new Properties();
            p.put("mail.smtp.port", "587");

            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com");

            String From = "nss.acacs@gmail.com";
            String EPass = "Arihant2020";
            String Sub = "Reset Password";
            String Txt = "Do Not Share Tis Mail With Anyone \n Your Password Is " + Pass + "";

            Session s = Session.getDefaultInstance(p, new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(From, EPass);
                }
            });
            Message M = prepareMessage(s, From, R, Sub, Txt);
            Transport.send(M);
            JOptionPane.showMessageDialog(null, "Email sended To " + R + "");
        } catch (MessagingException ex) {
            System.out.println("" + ex);
        }

    }

    private static Message prepareMessage(Session s, String From, String R, String Sub, String Txt) {
        try {
            Message M = new MimeMessage(s);
            M.setFrom(new InternetAddress(From));
            M.setRecipient(Message.RecipientType.TO, new InternetAddress(R));
            M.setSubject(Sub);
            M.setText(Txt);
            return M;

        } catch (Exception e) {
            System.out.println("" + e);
        }
        return null;
    }

    public void selestud(String s1, String s2) {
        try {
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/NSS_MGMT_SYS", "root", "password");
            String query1 = "Select * from Student where E_Id ='" + s1 + "' and Pass ='" + s2 + "'";
            PreparedStatement pst = con1.prepareStatement(query1);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                rnotxt.setText(rs.getString(1));
                nametxt.setText(rs.getString(2));
                if (rs.getString(3).equals(maleopt.getText())) {
                    maleopt.setSelected(true);

                }
                if (rs.getString(3).equals(femaleopt.getText())) {
                    femaleopt.setSelected(true);

                }
                if (rs.getString(3).equals(othersopt.getText())) {
                    othersopt.setSelected(true);

                }

                dob.setText(rs.getString(4));
                classcombo.setSelectedItem((rs.getString(5)).toString());
                nssunitcombo.setSelectedItem((rs.getString(6)).toString());
                mobtxt.setText(rs.getString(7));
                emailtxt.setText(rs.getString(8));
                aadhartxt.setText(rs.getString(9));
                weighttxt.setText(rs.getString(10));
                heighttxt.setText(rs.getString(11));
                guardtxt.setText(rs.getString(12));
                addrtxt.setText(rs.getString(13));
                pincdtxt.setText(rs.getString(14));
                blgrpcom.setSelectedItem((rs.getString(16)).toString());
                imgloc.setText(rs.getString(15));
                studyrtxt.setText(rs.getString(17));
                psd.setText(rs.getString(18));
                confpsd.setText(psd.getText());
                ImageIcon myimg = new ImageIcon(imgloc.getText());
                Image img1 = myimg.getImage();
                Image img2 = img1.getScaledInstance(studimg.getWidth(), studimg.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledimg = new ImageIcon(img2);
                studimg.setIcon(scaledimg);
            }
            updtbtn.setEnabled(true);
            rnotxt.setEnabled(true);
            nametxt.setEnabled(true);
            femaleopt.setEnabled(true);
            maleopt.setEnabled(true);
            othersopt.setEnabled(true);
            dob.setEnabled(true);
            classcombo.setEnabled(true);
            nssunitcombo.setEnabled(true);
            mobtxt.setEnabled(true);
            emailtxt.setEnabled(true);
            aadhartxt.setEnabled(true);
            weighttxt.setEnabled(true);
            heighttxt.setEnabled(true);
            guardtxt.setEnabled(true);
            addrtxt.setEnabled(true);
            pincdtxt.setEnabled(true);
            blgrpcom.setEnabled(true);
            imgloc.setEnabled(true);
            studyrtxt.setEnabled(true);
            psd.setEnabled(true);
            confpsd.setEnabled(true);
            studimg.setEnabled(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    void Exit() {
        int i = JOptionPane.showConfirmDialog(this, "Do You Want To Quit", "Quit", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            Optionform o1 = new Optionform();
            o1.setVisible(true);
            dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>*/
        try {
            UIManager.setLookAndFeel(new TextureLookAndFeel());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhartxt;
    private javax.swing.JLabel addrlbl;
    private javax.swing.JTextField addrtxt;
    private javax.swing.JLabel adhdarlbl;
    private javax.swing.JLabel adhdarlbl1;
    private javax.swing.JButton bckbtn;
    private javax.swing.JComboBox<String> blgrpcom;
    private javax.swing.JLabel bloodlbl;
    private javax.swing.JLabel bloodlbl1;
    private javax.swing.JLabel bloodlbl2;
    private javax.swing.JLabel bloodlbl3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> classcombo;
    private javax.swing.JPasswordField confpsd;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private datechooser.beans.DateChooserDialog dateChooserDialog4;
    private datechooser.beans.DateChooserDialog dateChooserDialog5;
    private com.github.lgooddatepicker.components.DatePicker dob;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JRadioButton femaleopt;
    private javax.swing.JLabel guardilbl;
    private javax.swing.JTextField guardtxt;
    private javax.swing.JLabel heightlbl;
    private javax.swing.JTextField heighttxt;
    private javax.swing.JLabel imgloc;
    private javax.swing.JButton imglodbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JRadioButton maleopt;
    private javax.swing.JTextField mobtxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel nsslbl1;
    private javax.swing.JLabel nsslbl3;
    private javax.swing.JComboBox<String> nssunitcombo;
    private javax.swing.JRadioButton othersopt;
    private javax.swing.JTextField pincdtxt;
    private javax.swing.JLabel pincodelbl;
    private javax.swing.JPasswordField psd;
    private javax.swing.JTextField rnotxt;
    private javax.swing.JLabel studimg;
    private javax.swing.JTextField studyrtxt;
    private javax.swing.JButton updtbtn;
    private javax.swing.JLabel weightlbl;
    private javax.swing.JTextField weighttxt;
    // End of variables declaration//GEN-END:variables
}
